### ISSUE TITLE
Suggestion for api-key

### ISSUE THREAD

**Issue by OrionRandD** [xenodium/chatgpt-shell#10]
Another suggestion, if you do not bother,
is to implement the function to call the api-key from a encrypted file...
The traditional one for Emacs is ".authinfo.gpg"
So that, the key won't be in plain text in Emacsen init.el(s) files...

**Comment by OrionRandD** [comment]
> (setq chatgpt_shell_api_key (getenv OPENAI_API_KEY)）

Ok. But, how can I write the chatgpt-api-key inside the "~/.authinfo.gpg" and then, prompt it to decrypt the file?
As it does with mu4e...

**Comment by xenodium** [comment]
Do you have some elisp snippets with how you’re handling this sort of thing for other use cases? This would help me bridge the gap.

**Comment by martinbaillie** [comment]
You can use EPA just fine for this. E.g.

`.authinfo.gpg`:
```text
machine api.openai.com login you password yourAPIkey
```

your config:
```elisp
(setq chatgpt-shell-openai-key
        (auth-source-pick-first-password :host "api.openai.com" :user "you"))
```

(@xenodium: thanks for this project, amazing as usual 👏🏻)

**Comment by OrionRandD** [comment]
> You can use EPA just fine for this. E.g.
> 
> `.authinfo.gpg`:
> 
> ```
> machine api.openai.com login you password yourAPIkey
> ```
> 
> your config:
> 
> ```emacs-lisp
> (setq chatgpt-shell-openai-key
>         (auth-source-pick-first-password :host "api.openai.com" :user "you"))
> ```
> 
> (@xenodium: thanks for this project, amazing as usual 👏🏻)

;; This still gives me nil

lets say I write this in .authinfo.gpg
machine api.opnai.com login myemail@fanthon.com foo password foobar sk-bar123foo321

;; this in my init.el

(setq chatgpt-shell-openai-key
        (auth-source-pick-first-password :host "api.openai.com" :user "foo"))

;; gives me NIL
;; and do not prompt for my .authinfo.gpg decription key

**Comment by xenodium** [comment]
> @xenodium: thanks for this project, amazing as usual 👏🏻

Thanks @martinbaillie!

> This still gives me nil

@OrionRandD can you share how you normally handle credentials in other packages (best to share a snippet).

**Comment by martinbaillie** [comment]
why have you got the foo and the foobar in there?

`machine api.opnai.com login [myemail@fanthon.com](mailto:myemail@fanthon.com) password sk-bar123foo321`

`(setq chatgpt-shell-openai-key(auth-source-pick-first-password :host "api.openai.com" :user "myemail@fanthon.com"))`

**Comment by xenodium** [comment]
> you normally handle credentials in _other_ packages

Thank. If you share how you normally do this in _other_ packages, I can see if I can help ya achieve a similar thing. However, I'll need to see some snippets for how you do it elsewhere.

**Comment by OrionRandD** [comment]
> 

Thx a lot. Worked...

**Comment by xenodium** [comment]
Thanks for helping out @martinbaillie! Closing.
