### ISSUE TITLE
Use the content of other babel block as variables inside a babel block

### ISSUE THREAD

**Issue by falematte** [xenodium/chatgpt-shell#102]
It would be helpful to pass to the babel blocks variable from other blocks as it is done e.g. with python blocks.

**Comment by xenodium** [comment]
Please share org snippets showcasing the feature request.

**Comment by falematte** [comment]
Some examples here https://orgmode.org/manual/Environment-of-a-Code-Block.html and here https://emacs.stackexchange.com/questions/19073/org-mode-passing-variables-between-code-blocks-without-sessions

**Comment by xenodium** [comment]
If I'm understanding correctly, the use case would be to replace some content inline the chatgpt-shell babel block. If so, wouldn't `noweb` be more appropriate here?

https://orgmode.org/manual/Noweb-Reference-Syntax.html

**Comment by xenodium** [comment]
It's been a little while... Here's an example on how to do it. Will close issue, but please reopen if needed.

```org
#+NAME: block1
#+BEGIN_SRC chatgpt-shell
Say hello
#+END_SRC

#+RESULTS: block1
Hello!

#+BEGIN_SRC chatgpt-shell :noweb yes
<<block1>>
What does the previous line say?
#+END_SRC

#+RESULTS:
The previous line says "Say hello".
```

**Comment by falematte** [comment]
This is not working... Why? Instead of the results noweb pass the elisp function itself...

#+NAME: copied_text_from_clipboard 
#+BEGIN_SRC emacs-lisp 
  (defun get-current-kill ()
  (current-kill 0))
  (get-current-kill)
#+END_SRC

#+RESULTS: copied_text_from_clipboard
: #+END_SRC




#+begin_src chatgpt-shell :noweb yes
  what is written here?

  <<copied_text_from_clipboard>> 
#+end_src

#+RESULTS:
This is a snippet of code written in the programming language Lisp.

**Comment by xenodium** [comment]
> This is not working... Why? Instead of the results noweb pass the elisp function itself...

Use `<<copied_text_from_clipboard()>>`

**Comment by falematte** [comment]
Thanks, my bad! Very useful!
