### ISSUE TITLE
[Feature Request] Being able to connect with chagpt-shell interactive shell to a babel block that we have runned 

### ISSUE THREAD

**Issue by falematte** [xenodium/chatgpt-shell#103]
This can be very usefull since I find that the :context t is not always reliable and it is often very useful to have long conversation with chatgpt to refine the result.

**Comment by xenodium** [comment]
> :context t is not always reliable

Could you add more details around this please? Are there specific chatgpt-shell bugs you are running into? Details on those would help me fix those. 

> conversations with ChatGPT to refine the result

This can be added via a different header maybe `:session`.

**Comment by falematte** [comment]
I have now back my subscription. Will try it out and post here. Sorry for the delay! Anyhow it appeared to me that sometime the :session was taken into account while other time it doesn't. It is hard to find a testing case but will do. Try to play with it a little bit in the meanwhile.

**Comment by xenodium** [comment]
I'm guessing this may now obsolete. Gonna go ahead and close. Please reopen if ya reckon we should look into it.
