### ISSUE TITLE
[Feature Request] Consider refactor code to support easily add other AI backends?

### ISSUE THREAD

**Issue by stardiviner** [xenodium/chatgpt-shell#107]
My ChatGPT account is banned. I found Poe https://poe.com/ChatGPT can be used.
Can chatgpt-shell support any other AI backends easily through simply changing API URL and API response parser function?

**Comment by xenodium** [comment]
>  any other AI backends easily through simply changing API URL

If there is an API URL that provides the same API request/response structure as ChatGPT, this would be doable. Could you provide that please?

If the API request/response structure is different, it would have to be implemented using `shell-maker` and that's bigger in scope.

**Comment by stardiviner** [comment]
I checked the Developer Tools when sending request to Poe ChatGPT. Here is the screenshot:

![Screenshot 2023-06-04 at 10 24 37@2x](https://github.com/xenodium/chatgpt-shell/assets/378699/7f11f88b-cd09-45b1-9148-e21ce2bf96e5)

I'm not familiar with web crawler technique. In my rough view, it has API for posting data, but I have not found the response. Hope someone knows this can analysis it.

**Comment by xenodium** [comment]
Thank you. Unless there's a legitimate and equivalent API available, with similar ChatGPT semantics/structure, it would be out of scope for this project.
