### ISSUE TITLE
How to reset context in the chatgpt-shell (not org-babel)?

### ISSUE THREAD

**Issue by falematte** [xenodium/chatgpt-shell#110]

**Comment by xenodium** [comment]
Have you tried this? https://github.com/xenodium/chatgpt-shell#clear-buffer

From shell: `ChatGPT(4/Programming)> reset`

Or `M-x chatgpt-shell-clear-buffer`

**Comment by xenodium** [comment]
Looks like this is already supported. Closing, but please reopen if it was for something else.
