### ISSUE TITLE
Set major mode to `chatgpt-shell-mode`

### ISSUE THREAD

**Issue by djliden** [xenodium/chatgpt-shell#114]
Context: I'm writing some YASnippets for `chatgpt-shell`.

During this process, I realized the active major mode in a chatgpt shell session is `shell-maker-mode`. I can imagine wanting to make snippets (or keybindings or other configuration changes) that are specific to particular shells, such as chatgpt-shell, made with shell-maker (and wanting to keep them separate), so it would be useful to me to have `chatgpt-shell-mode` active during a chatgpt-shell session.

I'm happy to work on this but wanted to raise it as an issue first to see if it would be a worthwhile change, if there was any context to be aware of, and if there were any ideas around implementation. e.g. should the name of the major mode be specified in shell-maker-config?

**Comment by xenodium** [comment]
Thanks for filing. I've been meaning to do something about this.

Added an experimental implementation in the `major-mode` branch: https://github.com/xenodium/chatgpt-shell/tree/major-mode

Could you give that a try please?

**Comment by djliden** [comment]
Looking good so far! I haven't tested comprehensively but invoking `M-x chatgpt-shell` and then checking the major mode with `C-h v major-mode` shows `chatgpt-shell-mode` on the `major-mode` branch. Changing the snippet directory from `shell-maker-mode` to `chatgpt-shell-mode` gives me the expected YASnippet functionality.

See #115 for some minor fixes to the new branch. Thanks for looking into this right away!

**Comment by xenodium** [comment]
Should be now merged in the `main` branch. Thanks for your help!
