### ISSUE TITLE
Can't make requests to `gpt-4-32k`

### ISSUE THREAD

**Issue by licht1stein** [xenodium/chatgpt-shell#117]
I tried editing setting `chatgpt-shell-model-versions` to `'("gpt-3.5-turbo" "gpt-3.5-turbo-0613" "gpt-4" "gpt-4-0613" "gpt-4-32k")` but I'm still getting an error:

```
The model: `gpt-4-32k` does not exist
```

But it should exist according to docs:

<img width="771" alt="image" src="https://github.com/xenodium/chatgpt-shell/assets/35418634/ad4076e4-6c0d-4f8f-bd03-d9c255f0ef78">

<img width="795" alt="image" src="https://github.com/xenodium/chatgpt-shell/assets/35418634/2b5a3d3b-82bf-4b0e-8db4-fe43eaff48d1">

Is there some sort of validation on submit?

**Comment by xenodium** [comment]
This validation/response is coming from OpenAI API and typically means the user hasn't got access to that model/version. Check out similar thread #55.

**Comment by licht1stein** [comment]
I see, thanks!
