### ISSUE TITLE
[Feature Request] Allow multiple org-babel source block contexts

### ISSUE THREAD

**Issue by jtmoulia** [xenodium/chatgpt-shell#120]
### Problem

chatgpt-shell's org-babel integration supports a single multi-block context, however sometimes it's useful to interleave multiple contexts.

### Solution

It feels like this was already planned for as the `:context` src block header already accepts an argument. The argument could be modified from a boolean  enabling the context to a string that specifies the context the src block belongs to.

This is one which I can probably take a crack at creating a PR for.

**Comment by xenodium** [comment]
Thanks for filing the feature request. Generally sounds good to me. Would be good to show the syntax we are aiming for. Something like the following?

```
#+begin_src chatgpt-shell :context "study 1"
  This will be included in the study
#+end_src

#+begin_src chatgpt-shell
  This will *not* be included in the study 
#+end_src

#+begin_src chatgpt-shell :context "study 1"
  This will also be included in the study 
#+end_src

#+begin_src chatgpt-shell :context "study 1"
  This will also be included in the study 
#+end_src
```

> This is one which I can probably take a crack at creating a PR for.

👍
