### ISSUE TITLE
[Question] `chatgpt-shell-mode-map` binding error

### ISSUE THREAD

**Issue by gopar** [xenodium/chatgpt-shell#125]
I have the following in my config (Important part is `:bind`:

```lisp
(use-package chatgpt-shell
  :ensure t
  :init
  (setq shell-maker-history-path (concat user-emacs-directory "var/"))
  :bind (:map chatgpt-shell-mode-map
              ("RET" . newline)
              ("M-RET" . shell-maker-submit))
  :custom
  (chatgpt-shell-openai-key
   (auth-source-pick-first-password :host "api.openai.com"))
  (chatgpt-shell-transmitted-context-length 5)
  (chatgpt-shell-model-versions '("gpt-3.5-turbo" "gpt-4" "gpt-3.5-turbo-16k")))
```

When I run this, I get an error that chatgpt-shell-mode-map is not defined. It doens't error out if I run this after I load chatgpt-shell though.

I know that I can use `S-<return>` but since I like to keep my keybidings similar in all my environments (eg for Slack, I also have M-RET as send message and regular RET as multiline)

Any ideas to how to get around this? Was thinking of adding a hook after chatgpt-shell loads but I also see that hooks are missing for when its loaded :)

P.S. Appreciate the new multishell support \o/

**Comment by xenodium** [comment]
1ec51235295f4685f6cc1a7601255fdcabffc1b3 should hopefully fix this. Lemme know if otherwise.

ps. May want `:commands chatgpt-shell` in `use-package` entry.
