### ISSUE TITLE
awesome prompts are not

### ISSUE THREAD

**Issue by Lenbok** [xenodium/chatgpt-shell#126]
I just saw the awesome prompts integration and thought I would give it a quick try. However, it looks like many of them are incomplete.

For example, the "Gnomist" prompt after loading by chatgpt-shell is "I want you to act as a gnomist. You will provide me with fun" however when you look in the awesome prompts repo, it should be "I want you to act as a gnomist. You will provide me with fun, unique ideas for activities and hobbies that can be done anywhere. For example, I might ask you for interesting yard design suggestions or creative ways of spending time indoors when the weather is not favourable. Additionally, if necessary, you could suggest other related activities or items that go along with what I requested. My first request is ""I am looking for new outdoor activities in my area"".". It seems the CSV parsing is isn't correctly dealing with commas (and maybe embedded quotes also).

**Comment by xenodium** [comment]
@dangom, who kindly contributed the parser in #114, mind taking a look at this issue?
