### ISSUE TITLE
Package not found on melpa

### ISSUE THREAD

**Issue by jvillasante** [xenodium/chatgpt-shell#130]
When I try to use `package-install` I get the following error:

```
Contacting host: melpa.org:443
package--with-response-buffer-1: https://melpa.org/packages/chatgpt-shell-20230709.2036.tar: Not found
```

Is this on Melpa? Alternatively, Is there a way to install from git with something like `package-vc-install`?

**Comment by xenodium** [comment]
Can you verify you can install other melpa packages? Maybe down when you tried? Should be there https://melpa.org/#/chatgpt-shell

**Comment by jvillasante** [comment]
Well, it is weird. First I tried with `M-x package-install` and that failed, but then `M-x list-packages` and install from there actually worked. Thanks!
