### ISSUE TITLE
[Question] How to open links?

### ISSUE THREAD

**Issue by gopar** [xenodium/chatgpt-shell#133]
When chatgpt spits out some links, emacs reformats them to org mode (which is good!) but unfortunately links no longer work when calling things like `org-open-at-point`. Any idea on how to make links open or even clickable?

Thanks

**Comment by xenodium** [comment]
> Any idea on how to make links open or even clickable?

No click as of now, but RET while on link should open it?

**Comment by xenodium** [comment]
> No click as of now

https://github.com/xenodium/chatgpt-shell/commit/1de7bfa6a34f20cca813006282d9a8f2ef291f95 should open clicks. Try updating and see if that works for ya. Please reopen if otherwise.

**Comment by gopar** [comment]
> No click as of now, but RET while on link should open it?

Ah! you are right, not sure what happened when I tried it. But I see you made it clickable as well. Thanks!
