### ISSUE TITLE
How to use chatgpt-shell through a http-proxy?

### ISSUE THREAD

**Issue by Spray27ds** [xenodium/chatgpt-shell#134]
Hello, is there a way do use chatgpt-shell through a http-proxy? I failed to figure it out my self.

**Comment by xenodium** [comment]
Have you seen the entry in the README? https://github.com/xenodium/chatgpt-shell#chatgpt-through-proxy-service and #73 ?

**Comment by Spray27ds** [comment]
First thanks for this nice work and the fast response! :-)
Yes, I saw it in the README and it seems not to address http-proxies or I don't understand it correctly. The same for https://github.com/xenodium/chatgpt-shell/issues/73
After digging further through the code I just got it working by customizing
"Chatgpt Shell Additional Curl Options" by adding two entries "-x" and "http://my proxy ip/"
I don't know if its the recommended way?

**Comment by xenodium** [comment]
I haven't used the proxy myself (@ stardiviner may have some pointers), but can I try to help diagnose... For that, I'll need more details please (like the entire snippet you used for setup and any relevant errors). Please check out https://github.com/xenodium/chatgpt-shell/blob/main/README.org#reporting-bugs for useful details you can share to help diagnose.

**Comment by stardiviner** [comment]
@Spray27ds Your said "http-proxy" is a "http proxy web service for chatgpt" or "http proxy server specified for cURL"?
If answer is the first, then you can follow README and my patch code to setting proxy service URL.
If answer is the second, then you need to setting `chatgpt-shell-additional-curl-options` to add cURL request through HTTP proxy.

**Comment by Spray27ds** [comment]
@stardiviner It's the second kind of proxy. So I had to set it in the curl-options. It woks fine now. Thanks for your help!

**Comment by xenodium** [comment]
@Spray27ds Would you be interested in sending a PR updating the README docs for other folks on the future?

**Comment by Spray27ds** [comment]
Yes I will try it. I'm quite new to github etc., so may be I need some 
help. Let's see.... :-)



Von:    "xenodium" ***@***.***>
An:     "xenodium/chatgpt-shell" ***@***.***>
Kopie:  "Spray27ds" ***@***.***>, "Mention" 
***@***.***>
Datum:  31.07.2023 13:44
Betreff:        Re: [xenodium/chatgpt-shell] How to use chatgpt-shell 
through a http-proxy? (Issue #134)



@Spray27ds Would you be interested in sending a PR updating the README 
docs for other folks on the future?
?
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: 
***@***.***>

**Comment by xenodium** [comment]
Sure. Happy to help. Another option... feel free to drop a comment here with a sample snippet + explanation and I can commit in your behalf (with credit to you in commit message).

**Comment by Spray27ds** [comment]
I just created my first PR. Hopefully it works...

**Comment by xenodium** [comment]
Merged! Thank you.
