### ISSUE TITLE
how to hook minor mode?

### ISSUE THREAD

**Issue by alej0varas** [xenodium/chatgpt-shell#136]
Hello,

I can't find a way to hook `auto-complete-mode` to `chatgpt-shell`. How can this be achieved?

Thanks

**Comment by xenodium** [comment]
Hi there. There’s currently no support for completion interaction. Having said that, there are reusable elisp APIs in chatgpt-shell  to send queries and get responses from ChatGPT. Would you be interested in building completion of sorts using these?

**Comment by alej0varas** [comment]
Hi, I just want to enable auto-complete mode as if I'm performing `M-x auto-complete-mode RET` while in the chatgpt-shell buffer, to get completions from the words that are already in the buffer.

**Comment by xenodium** [comment]
Got it.

`chatgpt-shell-mode-hook` is created for the `chatgpt-shell-mode` so something like the following should work.

```
(add-hook 'chatgpt-shell-mode-hook #'auto-complete-mode)
```

**Comment by xenodium** [comment]
Closing issue, but please reopen if that doesn't work for ya.
