### ISSUE TITLE
Suggestion - add string arguments to chatgpt-shell

### ISSUE THREAD

**Issue by OrionRandD** [xenodium/chatgpt-shell#14]
I've written this in my *scratch* buffer and evalutated it, but chatgpt-shell does not take ARGS... so, it did not work.
Could you add the possibility to get arguments from that?

(chatgpt-shell  "write an emacs script using the function find-youtubedl-links to download this youtube video hash SzA2YODtgK4")

This works only on the eshell prompt...

Also, if I type only the string:
"write an emacs script using the function find-youtubedl-links to download this youtube video hash SzA2YODtgK4"
and fire:
M-x chatgpt-shell
The expected behaviour should be:
Open chatgpt-shell prompt and execute the string... as it happens if we call a searching string on the *scratch* buffer and call w3m browser...

**Comment by xenodium** [comment]
> This works only on the eshell prompt.

I didn't find the eshell functionality.

```
(defun eshell (&optional arg)
  "Create an interactive Eshell buffer.
Start a new Eshell session, or switch to an already active
session.  Return the buffer selected (or created).

With a nonnumeric prefix arg, create a new session.

With a numeric prefix arg (as in `\\[universal-argument] 42 \\[eshell]'), switch
to the session with that number, or create it if it doesn't
already exist.

The buffer name used for Eshell sessions is determined by the
value of `eshell-buffer-name', which see.

Eshell is a shell-like command interpreter.  For more
information on Eshell, see Info node `(eshell)Top'."
  (interactive "P")
  (cl-assert eshell-buffer-name)
  (let ((buf (cond ((numberp arg)
		    (get-buffer-create (format "%s<%d>"
					       eshell-buffer-name
					       arg)))
		   (arg
		    (generate-new-buffer eshell-buffer-name))
		   (t
		    (get-buffer-create eshell-buffer-name)))))
    (cl-assert (and buf (buffer-live-p buf)))
    (pop-to-buffer-same-window buf)
    (unless (derived-mode-p 'eshell-mode)
      (eshell-mode))
    buf))
```
Could you point me to a function or docs?


I'm thinking maybe a separate function  can achieve a similar behaviour as described.

**Comment by xenodium** [comment]
Added. Check out `chatgpt-shell-prompt` and `chatgpt-shell-send-to-buffer`.
