### ISSUE TITLE
The best way to install the perfect chatgpt-shell by straight.el

### ISSUE THREAD

**Issue by Mercurius-Lee** [xenodium/chatgpt-shell#141]
(use-package shell-maker
               :straight (:type git :host github :repo: "xenodium/chatgpt-shell" :local-repo "chatgpt-shell" :files ("shell*.el")))

(use-package chatgpt-shell
               :straight (:type git :host github :repo: "xenodium/chatgpt-shell" :local-repo "chatgpt-shell" :files (:defaults (:exclude "shell*.el")))
               :config
               (setq chatgpt-shell-openai-key
                     (lambda ()
                       (auth-source-pick-first-password :host "api.openai.com"))))

**Comment by xenodium** [comment]
Thank you. Would you like to amend the README?

**Comment by xenodium** [comment]
I'm not a straight user.. Compared to what's in the README (contributed by others), what is the benefit to the suggestion? The README currently has the following, which seems simpler?

```
(use-package shell-maker
  :straight (:host github :repo "xenodium/chatgpt-shell" :files ("shell-maker.el")))

(use-package chatgpt-shell
  :requires shell-maker
  :straight (:host github :repo "xenodium/chatgpt-shell" :files ("chatgpt-shell.el")))
```

**Comment by kmcclosk** [comment]
(use-package shell-maker
  :straight (:type git :host github :repo: "xenodium/shell-maker" :local-repo "shell-maker" :files ("shell*.el")))

**Comment by Horrih** [comment]
Thanks for this issue, it put me on the right tracks.

This is what got it working for me

```elisp

**Comment by xenodium** [comment]
@Horrih thanks. Things changed when I split the project up into multiple repos for multi-model support https://lmno.lol/alvaro/chatgpt-shell-repo-splits-up

Added straight instructions: https://github.com/xenodium/chatgpt-shell?tab=readme-ov-file#straight
