### ISSUE TITLE
[feature request] default log directory and naming scheme C-x C-s

### ISSUE THREAD

**Issue by aiwebdude** [xenodium/chatgpt-shell#143]
I would love to set a folder for any transcript and either automatically have each appended with a unique (timestamp ... something) or path/transcript-(point ready to type). It seems if it prefills with a prior transcript path the log is not appended but overwrites?

thank you for this great little interface.

**Comment by xenodium** [comment]
Have you seen the options introduced in https://github.com/xenodium/chatgpt-shell/issues/112?

**Comment by aiwebdude** [comment]
No I did not and I thought I read through all of them.
