### ISSUE TITLE
How can I open chatgpt-shell with a query parameter?

### ISSUE THREAD

**Issue by madorian** [xenodium/chatgpt-shell#154]
Is there any way to call chatgpt-shell with a query?

I use org-babel a lot, but this places the results in the current buffer. 

I want to also have an option to open the currently opened chatgpt-shell and add a query

Is that possible?

**Comment by xenodium** [comment]
> Is there any way to call chatgpt-shell with a query?

Yep. There are a handful. All listed at https://github.com/xenodium/chatgpt-shell#chatgpt-shell-commands

For example:

`M-x chatgpt-shell-prompt`
`M-x chatgpt-shell-prompt-compose`

> I want to also have an option to open the currently opened chatgpt-shell and add a query

```emacs-lisp
(let ((chatgpt-shell-prompt-query-response-style 'shell))
  (chatgpt-shell-send-to-buffer "hello"))
```

**Comment by xenodium** [comment]
Gonna close, but please re-open if not yet answered.
