### ISSUE TITLE
No results from Azure GPT

### ISSUE THREAD

**Issue by NorwegianRockCat** [xenodium/chatgpt-shell#155]
I'm using an instance of an azure GPT by setting `chatgpt-shell-api-url-base`, `chatgpt-shell-api-url-path`, and `chatgpt-shell-auth-header` and it seems to work OK in that I can see that it decrypts my key, but instead of any results, I get these errors in the *Messages* buffer.

```
seq-first: Args out of range: [], 0 [6 times]
```

However, if I turn off streaming. The results seem to work fine (albeit you need to wait for the text to appear).

I tried to turn on logging with `shell-maker-logging` but then I never get a response printed (unless it takes *a lot* longer and I'm to impatient to wait for the response)

I guess it would be nice to have streaming work as when I run the curl command on the command-line (with proper escaping), it does return a stream of content (which is why I guess we get "out of range" so many times on the console.

Any extra information I can provide or something I overlooked?

**Comment by xenodium** [comment]
Sorry, I don't have access to azure gpt. Does https://github.com/xenodium/chatgpt-shell/pull/138 help at all?

**Comment by NorwegianRockCat** [comment]
Yes, #138 is necessary and what I use. I am using the latest chatpgt-shell from melpa. I could send a result of the streams from a curl run if that would help in debugging? I suspect the stream JSON from Azure looks just a little different from the stock OpenAI JSON and that might be causing the issue?

**Comment by goofansu** [comment]
#138 makes azure API works, the problem in this ticket occurs when parsing the streaming response. Set `chatgpt-shell-streaming nil` is a workaround.

**Comment by mateialexandru** [comment]
I'm also interested in this @xenodium ! how can I help?

**Comment by mateialexandru** [comment]
@NorwegianRockCat any luck?

**Comment by goofansu** [comment]
FYI, the response with `stream: true` are chunked:

```shell
❱ curl "https://mygpt.openai.azure.com/openai/deployments/gpt-4/chat/completions?api-version=2023-07-01-preview" \
        -H "Content-Type: application/json" \
        -H "api-key: API_KEY" \
        -d "{
    \"messages\": [{\"role\":\"system\",\"content\":\"hi\"}],
    \"max_tokens\": 800,
    \"temperature\": 0.7,
    \"frequency_penalty\": 0,
    \"presence_penalty\": 0,
    \"top_p\": 0.95,
    \"stop\": null,
    \"stream\": true
  }"

data: {"id":"","object":"","created":0,"model":"","prompt_filter_results":[{"prompt_index":0,"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"choices":[]}

data: {"id":"chatcmpl-8V1mzvFANVW81eY6AMkrEgfIMuFKN","object":"chat.completion.chunk","created":1702405737,"model":"gpt-4","choices":[{"index":0,"finish_reason":null,"delta":{"role":"assistant"},"content_filter_results":{}}],"system_fingerprint":"fp_50a4261de5"}

data: {"id":"chatcmpl-8V1mzvFANVW81eY6AMkrEgfIMuFKN","object":"chat.completion.chunk","created":1702405737,"model":"gpt-4","choices":[{"index":0,"finish_reason":null,"delta":{"content":"Hello"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"system_fingerprint":"fp_50a4261de5"}

data: {"id":"chatcmpl-8V1mzvFANVW81eY6AMkrEgfIMuFKN","object":"chat.completion.chunk","created":1702405737,"model":"gpt-4","choices":[{"index":0,"finish_reason":null,"delta":{"content":"!"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"system_fingerprint":"fp_50a4261de5"}

data: {"id":"chatcmpl-8V1mzvFANVW81eY6AMkrEgfIMuFKN","object":"chat.completion.chunk","created":1702405737,"model":"gpt-4","choices":[{"index":0,"finish_reason":null,"delta":{"content":" How"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"system_fingerprint":"fp_50a4261de5"}

data: {"id":"chatcmpl-8V1mzvFANVW81eY6AMkrEgfIMuFKN","object":"chat.completion.chunk","created":1702405737,"model":"gpt-4","choices":[{"index":0,"finish_reason":null,"delta":{"content":" can"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"system_fingerprint":"fp_50a4261de5"}

data: {"id":"chatcmpl-8V1mzvFANVW81eY6AMkrEgfIMuFKN","object":"chat.completion.chunk","created":1702405737,"model":"gpt-4","choices":[{"index":0,"finish_reason":null,"delta":{"content":" I"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"system_fingerprint":"fp_50a4261de5"}

data: {"id":"chatcmpl-8V1mzvFANVW81eY6AMkrEgfIMuFKN","object":"chat.completion.chunk","created":1702405737,"model":"gpt-4","choices":[{"index":0,"finish_reason":null,"delta":{"content":" assist"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"system_fingerprint":"fp_50a4261de5"}

data: {"id":"chatcmpl-8V1mzvFANVW81eY6AMkrEgfIMuFKN","object":"chat.completion.chunk","created":1702405737,"model":"gpt-4","choices":[{"index":0,"finish_reason":null,"delta":{"content":" you"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"system_fingerprint":"fp_50a4261de5"}

data: {"id":"chatcmpl-8V1mzvFANVW81eY6AMkrEgfIMuFKN","object":"chat.completion.chunk","created":1702405737,"model":"gpt-4","choices":[{"index":0,"finish_reason":null,"delta":{"content":" today"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"system_fingerprint":"fp_50a4261de5"}

data: {"id":"chatcmpl-8V1mzvFANVW81eY6AMkrEgfIMuFKN","object":"chat.completion.chunk","created":1702405737,"model":"gpt-4","choices":[{"index":0,"finish_reason":null,"delta":{"content":"?"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"system_fingerprint":"fp_50a4261de5"}

data: {"id":"chatcmpl-8V1mzvFANVW81eY6AMkrEgfIMuFKN","object":"chat.completion.chunk","created":1702405737,"model":"gpt-4","choices":[{"index":0,"finish_reason":"stop","delta":{},"content_filter_results":{}}],"system_fingerprint":"fp_50a4261de5"}

data: [DONE]
```

**Comment by mateialexandru** [comment]
I gave it, although I am not clear on what other customizations are needed...

Does anyone have a good example of what to use in the URL, azure deployment path, etc?

(use-package! chatgpt-shell
  :custom
   (chatgpt-shell-api-url-base "<my azure URL>")
   (chatgpt-shell-api-url-path "<the path to my azure deployment>")
   (chatgpt-shell-curl-auth-header "api-key: ")))

**Comment by goofansu** [comment]
@mateialexandru If you've got your deployment's endpoint and api key, let's say:

- Endpoint: `https://{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}/chat/completions?api-version={api-version}`
- API key: `api-key`

Configure `chatgpt-shell` like below:

```elisp
(setq chatgpt-shell-openai-key "{api-key}")
(setq chatgpt-shell-api-url-base "https://{your-resource-name}.openai.azure.com")
(setq chatgpt-shell-api-url-path "openai/deployments/{deployment-id}/chat/completions?api-version={api-version}")
(setq chatgpt-shell-auth-header (lambda () (format "api-key: %s" (chatgpt-shell-openai-key))))
(setq chatgpt-shell-streaming t)
```

FYI, this is my configuration: https://git.sr.ht/~goofansu/emacs-config/tree/01525d1d8ecb04520e050703271c67a12584726a/item/lisp/init-network-tools.el#L8-14

**Comment by NorwegianRockCat** [comment]
@goofansu I tried your patch in #174, and it works great for me. Thank you! It is nice to get streaming output instead of waiting for the whole chunk. So, I approve of the PR (whatever weight that provides).

Maybe there should be a separate commit for documenting Azure set-ups in the module? That way people don't have to through issues.

**Comment by goofansu** [comment]
@NorwegianRockCat updated README

**Comment by goofansu** [comment]
@xenodium #174 is ready

**Comment by xenodium** [comment]
@goofansu Thanks for pinging and sorry for the delay. We may need to tweak the PR a little. See https://github.com/xenodium/chatgpt-shell/pull/174#issuecomment-1864622448

**Comment by mateialexandru** [comment]
Thank you! I had that setup but I was getting empty responses :( I guess the model was the problem, and it was failing silently. 

Trying it with the latest changes now! Thank you @goofansu @xenodium @NorwegianRockCat !

**Comment by xenodium** [comment]
> Trying it with the latest changes now! 

@mateialexandru Do you mean, you patched `chatgpt-shell--extract-chatgpt-response` with the diff in https://github.com/xenodium/chatgpt-shell/pull/174#issuecomment-1864722433 Did that work for you?

**Comment by mateialexandru** [comment]
@NorwegianRockCat @goofansu @xenodium Yes, pulled latest #174 and adjusted my configuration and I confirm it works for my Azure OpenAI deployment :) The instructions from @goofansu should be included in the README for this Azure OpenAI scenario.

Thanks!

**Comment by mateialexandru** [comment]
@xenodium I didn't apply any other manual changes, maybe they were already applied in the latest #174 ? 
I haven't noticed any bugs or inconsistencies with the latest changes in this PR.

**Comment by xenodium** [comment]
@NorwegianRockCat Great to hear. Thanks for trying it out. Will wait for @goofansu's PR tweaks and and then merge.

**Comment by mateialexandru** [comment]
Thank you! It all works as expected!
