### ISSUE TITLE
[Q] Is Dall-E 3 supported?

### ISSUE THREAD

**Issue by NightMachinery** [xenodium/chatgpt-shell#157]
Is Dall-E 3 supported? How do I use it in org-babel?

**Comment by xenodium** [comment]
It wasn't but https://github.com/xenodium/chatgpt-shell/commit/97b43d27906d8589c9c38363002c03735150839a added suport for it.

Use `dall-e-shell-model-version` if using the shell, otherwise in babel:

```org
#+begin_src dall-e-shell :version dall-e-3
  fluffy clouds
#+end_src
```

**Comment by NightMachinery** [comment]
@xenodium DallE3 rewrites the user prompt before creating an image. I wonder if the API returns this new prompt? If so, including it in the output can be useful. The ChatGPT website does this. (Click on any generated image to see its rewritten prompt.)

**Comment by xenodium** [comment]
Just checked. It comes back in `revised_prompt`. Added it to the shell. Need to think about how ot handle for babel.

**Comment by xenodium** [comment]
Added. Use `:results both` in babel.

```org
#+begin_src dall-e-shell :version dall-e-3 :results both
  Cuberpunk alleyway.
#+end_src

: /var/folders/m7/ky091cp56d5g68nyhl4y7frc0000gn/T/1701219872.png
:
: A dark, grungy, and steamy narrow alleyway set in a cyberpunk cityscape.
```
