### ISSUE TITLE
[FR] Streaming for `ob-chatgpt-shell`

### ISSUE THREAD

**Issue by NightMachinery** [xenodium/chatgpt-shell#158]
Without streaming, it's just too slow.

**Comment by xenodium** [comment]
Thanks for filing. Unfortunately, it's waiting for server response. Not too much we can do there.

**Comment by NightMachinery** [comment]
@xenodium The server supports streaming output though? See [here](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb).

**Comment by xenodium** [comment]
Ah sure. The shell is already using the streaming API but babel doesn't quite lend itself for streaming out of the box, AFAIK.

**Comment by NightMachinery** [comment]
@xenodium `emacs-jupyter` correctly streams all output in babel. In fact, I am currently using Jupyter Python for streaming ChatGPT outputs. Here is an example to verify the streaming support:

```
#+begin_src jupyter-python :kernel py_base :session emacs_py_1 :async yes :exports both
import time

print("1")
time.sleep(4)
print("2")
#+end_src

#+RESULTS:
: 1
: 2
```

**Comment by xenodium** [comment]
If I'm understanding correctly, emacs-jupyter built its own async support since it's not built into babel itself, but I'm not familiar with jupyter. This is a little out of scope for me. Patches welcome though.
