### ISSUE TITLE
[BUG] Does NOT remove previous response when regenerating

### ISSUE THREAD

**Issue by NightMachinery** [xenodium/chatgpt-shell#159]
Unless I add `:wrap "src markdown"`, the previous results won't be deleted when a block is rerun.

**Comment by xenodium** [comment]
Thanks for filing. Will need more details please. https://github.com/xenodium/chatgpt-shell#reporting-bugs

**Comment by NightMachinery** [comment]
I don't really care about this bug, as I want the result to be wrapped around a markdown block anyhow. Thanks!
