### ISSUE TITLE
Symbol’s function definition is void: seq-first

### ISSUE THREAD

**Issue by ayman** [xenodium/chatgpt-shell#16]
Everything looks good (curl request goes through and all).  Then I get:

`Symbol’s function definition is void: seq-first`

from 

```
(defun chatgpt-shell--extract-content (json)
  "Extract ChatGPT response from JSON."
  (when-let (parsed (chatgpt-shell--json-parse-string json))
    (string-trim
     (map-elt (map-elt (seq-first (map-elt parsed 'choices))
                       'message)
              'content))))
```

I don't see `seq-first` in the [seq doc](https://www.gnu.org/software/emacs/manual/html_node/elisp/Sequence-Functions.html).  Am I missing something?

Running: `GNU Emacs 28.2 (build 1, aarch64-apple-darwin22.3.0, NS appkit-2299.40 Version 13.2.1 (Build 22D68)) of 2023-02-24`.

**Comment by xenodium** [comment]
Emacs 28.2 should already have it (since 27.1). But I was missing an import. Could you try again with latest please?

**Comment by ayman** [comment]
Pulled `f7a5390..6dfa85f`.  I see the imports:

```
(require 'comint)
(require 'map)
(require 'markdown-mode)
(require 'seq)
```

Same error. 

```
error in process sentinel: map-elt: Symbol’s function definition is void: seq-first
error in process sentinel: Symbol’s function definition is void: seq-first
```

I'm seeing `seq.el` version 1.12 (Package version 20151121.1017).

**Comment by xenodium** [comment]
Could you check if you happen to have another version of seq.el installed in addition to the built-in one? I'm also on Emacs 28.2 and it has a newer seq version (2.23) and can also see `seq-first in it`:

<img width="953" alt="Screenshot 2023-03-23 at 19 34 55" src="https://user-images.githubusercontent.com/8107219/227330735-e2bac2fe-f898-40a4-9597-a9aac23137ac.png">

If you do have one, maybe try `M-x package-delete seq`?

**Comment by ayman** [comment]
Yup! There was an older version of seq in the elpa folder.  Deleted that and the built in version (2.23) is now loading properly. Thanks!
