### ISSUE TITLE
Are there some examples with porxy?

### ISSUE THREAD

**Issue by arstum** [xenodium/chatgpt-shell#163]
```
Using ChatGPT through HTTP(S) proxy

Behind the scenes chatgpt-shell uses curl to send requests to the openai server. If you use ChatGPT through a HTTP proxy (for example you are in a corporate network and a HTTP proxy shields the corporate network from the internet), you need to tell curl to use the proxy via the curl option -x http://your_proxy. One way to do this is to set the proxy url via the customizable variable chatgpt-shell-additional-curl-options. If you set this variable via the Emacs Customize interface you should insert two separate items -x and http://your_proxy. See the curl manpage for more details and further options.
```

I can't write the correct parameters.Can provide some examples?

**Comment by arstum** [comment]
emacs in archlinux

(package-install 'chatgpt-shell)
(package-install 'shell-maker)
(require 'chatgpt-shell)
(require 'shell-maker)
(setq chatgpt-shell-openai-key "sess-XXXXXXXXXXXXXXXX")
(setq chatgpt-shell-additional-curl-options "--socks5 127.0.0.1:8080")

**Comment by xenodium** [comment]
Have you seen https://github.com/xenodium/chatgpt-shell#chatgpt-through-proxy-service ?

Unfortunately, I'm not using the proxy myself so I can't give you an example. Perhaps @Spray27ds  @stardiviner  @Vonfry who have been in touch about it and contributed PRs can help?

https://github.com/xenodium/chatgpt-shell/issues/134
https://github.com/xenodium/chatgpt-shell/pull/152

**Comment by xenodium** [comment]
@arstum I see you closed the issue. Thanks. I'm hoping you found the solution. Mind sharing how you fixed things (or the example you used), so I can better document things if needed?

**Comment by kinredon** [comment]
@arstum Hi, I  have met the same problem, do you solve this?
