### ISSUE TITLE
You need curl version 7.76 or newer.

### ISSUE THREAD

**Issue by kinredon** [xenodium/chatgpt-shell#165]
I have updated my curl, but the error still occurs. Why does this happen?

![image](https://github.com/xenodium/chatgpt-shell/assets/39270545/e4f8b53f-4d97-4b4a-970f-251ff4fd64d9)

![image](https://github.com/xenodium/chatgpt-shell/assets/39270545/5397a534-d9b1-4759-8a52-61b2794e7d04)

**Comment by kinredon** [comment]
Yes, I found the emacs uses the old version of curl and does not use the new version of curl that is installed by homebrew. 

I fixed this issue by specifying the curl version as follows:

```
(setq exec-path (cons "/usr/local/opt/curl/bin/" exec-path))

(setenv "PATH" (concat "/usr/local/opt/curl/bin/:" (getenv "PATH")))
```

**Comment by kinredon** [comment]
@xenodium But there is a new error about the proxy, I use the ClashX and have the socks5 proxy. I set the proxy following the instructions in the readme. 

`-x socks5://127.0.0.1:1088`, but it does not work.

**Comment by mateialexandru** [comment]
For the record, I had this issue in WSL, with Ubuntu 22.04 LTS where curl version is 7.68 by default.

I had to add to /etc/apt/sources.list the following lines:
deb http://cz.archive.ubuntu.com/ubuntu lunar main
deb http://security.ubuntu.com/ubuntu lunar-security main

And then I was able to install a newer version of CURL that is > 7.76

**Comment by runekaagaard** [comment]
On ubuntu 20.04 you can `snap install curl` and then add `export PATH=/snap/bin:$PATH` to your `.bashrc` file.
