### ISSUE TITLE
Incorrect/Unhelpful Customization Types

### ISSUE THREAD

**Issue by swflint** [xenodium/chatgpt-shell#167]
I will likely submit PRs for the following, however, the following customize variables don't have helpful customization types.

 - `chatgpt-shell-language-mapping` (could be `alist`)
 - `chatgpt-shell-babel-headers`
 - `chatgpt-shell-source-block-actions` (probably should be a `repeat` type, but maybe an `alist`)
 - `chatgpt-shell-system-prompts` (could be improved with `:tag`)

**Comment by xenodium** [comment]
Thanks for submitting! yes please. Pray super welcome.
