### ISSUE TITLE
Cannot upgrade to version 4

### ISSUE THREAD

**Issue by emacs-elements** [xenodium/chatgpt-shell#173]
The package works fine as long I use version 3 of chatgpt. Though I have now upgraded to when I try to use version 4 I get this error:

`The model `gpt-4-1106-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.`

I have gotten a new api key but it makes no difference. None of the following work:

```
gpt-4-1106-preview
gpt-4-0613
gpt-4
```

**Comment by xenodium** [comment]
> The model gpt-4-1106-preview does not exist or you do not have access to it

This error is coming from the OpenAI API itself. Need to upgrade API at OpenAI.

>  Though I have now upgraded to

I'm guessing you upgraded web UI access but not the API registration? This confused me too.

Check out existing discussions https://github.com/xenodium/chatgpt-shell/issues/55

**Comment by emacs-elements** [comment]
After upgrading my ChatGPT account, I upgrade my key here: https://platform.openai.com/api-keys. I can only access earlier models, not chatgpt-4 or later.

**Comment by xenodium** [comment]
Unfortunately, not a whole lot we can do from the Emacs package. Needs to be sorted with OpenAI.

Have you seen this?

https://community.openai.com/t/how-to-get-access-to-gpt-4-via-api/555649

```
You’ll need to complete at least one successful API payment before you’ll be granted access to the newer models. You can pre-pay; I put $5 in and was granted GPT-4 access in a few minutes after the payment processed; and GPT-4-1106-preview shortly thereafter (when it was released). Go to [platform.openai.com](http://platform.openai.com/) - then in the left sidebar, click Settings, then Billing, and there will be a button labeled ‘Add to credit balance’ that will let you fund your API account. That should do the trick.
```

Tried to prepay?

**Comment by emacs-elements** [comment]
Thank you. This solution worked for me. It appears that having a paid subscription to chatgpt does not automatically allow access to the API. I made a payment and it seems everything is working now.

**Comment by xenodium** [comment]
Good to hear!
