### ISSUE TITLE
Logs in *Messages*

### ISSUE THREAD

**Issue by kjnez** [xenodium/chatgpt-shell#178]
This is after restoring a session from a transcript:

> Can’t guess python-indent-offset, using defaults: 4 [2 times]
> Invalid face reference: org-level-3 [5 times]

**Comment by xenodium** [comment]
Sorry it's taken me long to reply. I've just ran a restore and couldn't reproduce. Gonna close issue, but please reopen if you're still seeing this. If you have a transcript you can share, that'd be helpful too.
