### ISSUE TITLE
selecting prompt for compose

### ISSUE THREAD

**Issue by vzaliva** [xenodium/chatgpt-shell#180]
When using chatgptshell-compose via keybinding with `C-u` prefix it currently just clears the buffer. It would be nice if when invoked via prefix it would offer me a magit-like menu to choose a prompt.

**Comment by xenodium** [comment]
Nice suggestion. Maybe as `C-u C-u` since needing to clear history may be more common.

**Comment by xenodium** [comment]
`chatgpt-shell-prompt-compose` now allows swapping system prompts via `chatgpt-shell-prompt-compose-swap-system-prompt` (C-c C-s).
