### ISSUE TITLE
shell maker cursor not returning properly at the end of prompt

### ISSUE THREAD

**Issue by rajasegar** [xenodium/chatgpt-shell#181]
When I use the sample shell maker code in Emacs 29, the cursor is on the next line instead of at the end of the prompt after entering any command:
<img width="343" alt="Screenshot 2024-01-02 at 2 02 35 PM" src="https://github.com/xenodium/chatgpt-shell/assets/2083049/4f201ace-b4a4-4aec-9a9e-29f76cd75798">

**Comment by xenodium** [comment]
Thanks for reporting. Should be fixed now. Give [0a25e18](https://github.com/xenodium/chatgpt-shell/commit/0a25e185a89044ee0391def5c58b9d8f4a2e9a56) a try.
