### ISSUE TITLE
Closing the chatgpt-shell compose window while answer is streaming in 'hangs' Emacs until finished and produces many errors

### ISSUE THREAD

**Issue by DivineDominion** [xenodium/chatgpt-shell#187]
When  a long answer comes in but you close the compose window with <kbd>q</kbd>, Emacs complains and refuses input until the answer is finished:

```
error in process filter: Selecting deleted buffer [258 times]
error in process sentinel: Selecting deleted buffer [2 times]
```

**Comment by xenodium** [comment]
Eeeek. That's rough. Sorry. Thanks for filing. Lemme look into it...

**Comment by DivineDominion** [comment]
Can confirm it works, thank you

**Comment by xenodium** [comment]
> The streaming of answers arguably should not stop to the main buffer?

good point. the shell now continues to stream after killing the compose buffer as of [3bf5464](https://github.com/xenodium/chatgpt-shell/commit/3bf5464d2c7354f212446e9af151749aef80c2c9).
