### ISSUE TITLE
Note that `emacs` needs to be compiled `--with-json` support

### ISSUE THREAD

**Issue by jflatow** [xenodium/chatgpt-shell#19]
I love this approach! I just wanted to note that you need to have emacs compiled with json support for posterity.

**Comment by xenodium** [comment]
> I love this approach!

Thank you. Glad you like it!

>  I just wanted to note that you need to have emacs compiled with json support for posterity.

It should now fail gracefully.

```
ChatGPT> Hello

Emacs needs to be compiled with --with-json

```

**Comment by shervinsafavi** [comment]
Is there anyway around it to use a normally compiled Emacs?

In general (just curious), what are the advantage of this special version/compilation of Emacs (or it's just the default with more recent Emacs)?

**Comment by xenodium** [comment]
Shouldn't be a requisite anymore. Did it ask you for it? Main benefit is speed.

**Comment by shervinsafavi** [comment]
You are right, I wasn't working with the most recent version of your code. 

Also thanks for noting the benefit of compiled Emacs with json support (I didn't know)
