### ISSUE TITLE
Is there a way to start a new session AND clear the chat buffer?

### ISSUE THREAD

**Issue by tupini07** [xenodium/chatgpt-shell#192]
Hi, thanks for this great package!

This is more of a question than a feature, but I can't seem to find a way to start a new chat session (clear all past messages in memory) as well as clear the chat buffer itself. 

I've seen that I can run `M-x chatgpt-shell` to accomplish the first and clear all memory of my messages (so, in practice starting a new chat session), however the existing messages from the chat buffer are not cleared. Instead I need to type `clear` to clear the buffer (OR close the buffer and then start a new shell, which is more cumbersome). 

If there's no way to do this in one step then it would be nice to add one!

**Comment by xenodium** [comment]
> Hi, thanks for this great package!

Thanks. Glad you like it.

> I can't seem to find a way to start a new chat session 

Invoking `chatgpt-shell` always goes to the existing chat (along with existing history), but if you invoke with a prefix (ie. `C-u`), it should start a new chat for you (clean history).

Does that help?

**Comment by tupini07** [comment]
Thanks yes that's exactly what I was looking for 🤗 Closing
