### ISSUE TITLE
chatgpt-shell-describe-image fails with the error "/usr/bin/emacs: /usr/bin/curl: Argument list too long"

### ISSUE THREAD

**Issue by djr7C4** [xenodium/chatgpt-shell#197]
This occurs when attempting to use this command to describe any image in `image-mode` or when an image is marked in `dired-mode`.

**Comment by xenodium** [comment]
Have you updated to the latest? Should hopefully be addressed by https://github.com/xenodium/chatgpt-shell/commit/2657079cb4d83d4fdcc0de4d5d225ed7e960ac9b

**Comment by djr7C4** [comment]
I'm using version 0.49.1 of shell-maker and version 1.0.5 of chatgpt-shell from commit 6e96b71f47ee9b456b1372e1670b9abbe47de3e2 (the tip of main 7 days ago) so they should include that commit. The error seems to be somewhat specific to this function. I haven't had any issues with any other the others that I've tried.

**Comment by xenodium** [comment]
Will need to look more into it. Are you able to share the image you used or at least the size?

**Comment by djr7C4** [comment]
The error does seem to be related to larger images. This one seems to cause it for example: https://en.wikipedia.org/wiki/Emacs#/media/File:Emacs-linux-console.png

**Comment by djr7C4** [comment]
On my system, `(length json)` is `252796` so a file is not used and inlining is employed. When I force it to use a file by replacing `(when (> (length json) 262144) ...)` with `(when t ...)`, it works correctly. 

The problem does not seem to be related to my configuration as I tested with a minimal config that only has `chatgpt-shell` installed.

**Comment by xenodium** [comment]
Thank you. This helps. Could you also post the value of running from command line:

`expr $(getconf ARG_MAX) / 4`

Btw, could you post OS details too?

**Comment by djr7C4** [comment]
`expr $(getconf ARG_MAX) / 4` is `524288`. I am running GNU Emacs 29.1 on Arch Linux (kernel 6.5.3-arch1-1).

**Comment by djr7C4** [comment]
I dug into this a bit more. It looks like the limit should be ARG_MAX / 16 - 1 = 131071 instead of 262144 for Linux. I verified that on my system, this is the maximum length of an argument.

I found this stackexchange thread that discusses it in more detail: https://unix.stackexchange.com/questions/120642/what-defines-the-maximum-size-for-a-command-single-argument

One issue however, is that this limit will vary across different systems (even if we only consider *nix flavors). Maybe it would be simpler to simply always use a file (or give the user a configuration option that causes a file to always be used).

**Comment by xenodium** [comment]
Thanks for this! I have a patch to basically use a json file at all times and drop the check. I'll see if I can push shortly.

**Comment by xenodium** [comment]
Ok. Give this latest a try. Please reopen if still an issue.

**Comment by djr7C4** [comment]
Thanks! The tip of main seems to be working now.
