### ISSUE TITLE
How can I send a line?

### ISSUE THREAD

**Issue by madorian** [xenodium/chatgpt-shell#203]
I'm trying to send the current line to the chatgpt-shell, like: 

```
(defun send-line-to-chatgpt-shell-main ()
  (interactive)
  (b0ef/select-line)
  (chatgpt-shell-send-region nil)
  (deactivate-mark t)
)
```

The problem is that the mark is still active in the buffer, so when I return to the buffer, I have to deactivate-mark with ESC

I'm not really sure what's the best way to do this, but I'm sure you have a solution;)

**Comment by xenodium** [comment]
Sorry for the delay. Take a look at `chatgpt-shell-send-region` implementation. Modify it to something like this:

```emacs-lisp
(defun chatgpt-shell-send-current-line ()
  (interactive)
  (let ((chatgpt-shell-prompt-query-response-style 'shell)
        (line-text (buffer-substring
                    (line-beginning-position)
                    (line-end-position))))
    (chatgpt-shell-send-to-buffer line-text)))
```

The above function should do it. Gonna close issue, but please reopen if otherwise.
