### ISSUE TITLE
Installing dall-e-shell gives a warning/error

### ISSUE THREAD

**Issue by jozilla** [xenodium/chatgpt-shell#204]
After install dall-e-shell, I get the following:

`Warning (bytecomp): reference to free variable ‘dall-e-shell-mode-map’`

I'm also a bit unsure if I should use two use-package declarations, one for chatgpt-shell and one for dall-e-shell?
```
;; ChatGPT
(use-package chatgpt-shell
  :ensure t
  :custom
  ((chatgpt-shell-openai-key
    (lambda ()
      (auth-source-pick-first-password :host "api.openai.com")))))
;; DALL-E
(use-package dall-e-shell
  :ensure t
  :custom
  ((dalle-shell-openai-key
    (lambda ()
      (auth-source-pick-first-password :host "api.openai.com")))))
```

Somehow the openai key isn't set for dall-e.

**Comment by xenodium** [comment]
> I should use two use-package declarations, one for chatgpt-shell and one for dall-e-shell?

Two declarations. You have it right.

> Somehow the openai key isn't set for dall-e.

There's a typo in the snippet: `dalle-shell-openai-key` -> `dall-e-shell-openai-key`.

**Comment by jozilla** [comment]
D'oh, stupid mistake about the misspelling, thanks so much!
