### ISSUE TITLE
curl: (48) An unknown option was passed in to libcurl

### ISSUE THREAD

**Issue by ipocentro87** [xenodium/chatgpt-shell#205]
Hi all, I've been trying to get `chatgpt-shell` work but I got stuck here:

```
ChatGPT(4-0125-preview/General)> test
curl: (48) An unknown option was passed in to libcurl
```

I've been using curl 8.7.1 (both on terminal and Emacs). Do you know where the problem comes from? Thanks in advance :pray: !

Marcello

**Comment by xenodium** [comment]
Hi there. Sounds like the issue is in the version mismatch. The only curl requirement needed is to run curl 7.76 or newer.

**Comment by xenodium** [comment]
Sounds like this may no longer be an issue after sorting out libcurl installation. Gonna close issue.
