### ISSUE TITLE
You exceeded your current quota

### ISSUE THREAD

**Issue by salehawal** [xenodium/chatgpt-shell#206]
Error Messege:
"
ChatGPT(3.5t/General)> who are you

You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs:
https://platform.openai.com/docs/guides/error-codes/api-errors.curl: (22) The requested URL returned error:429
";

i have tried all the 3.5 versions and all of them are not working!!!

**Comment by xenodium** [comment]
Needs to be sorted out with OpenAI and your plan/billing with them. Check out other threads for how they sorted it out.

https://github.com/xenodium/chatgpt-shell/issues/69#issuecomment-1525335720
https://github.com/xenodium/chatgpt-shell/issues/173
