### ISSUE TITLE
[minor] Is it possible re-export the `shell-maker-transcript-default-path` too?

### ISSUE THREAD

**Issue by ccqpein** [xenodium/chatgpt-shell#212]
It looks like `chatgpt-shell` is using the `shell-maker-save/restore-session-transcript` functions and it checks the `shell-maker-transcript-default-path`. Could we export this setting to `chatgpt-shell` so that I can customize the path through configuration?

P.S.: Since `chatgpt-shell` requires `shell-maker`, I can define the setting in `shell-maker`. If you think it's unnecessary, that's fine with me too.

**Comment by xenodium** [comment]
`(setq shell-maker-transcript-default-path "~/My/favourite/path")` should work for any shell depending on `shell-maker`. Does it work for you in `chatgpt-shell`?

I've been slowly moving chatgpt-shell things into shell-maker, though I need to figure out what's the best strategy to expose shell-maker settings to its clients also.

**Comment by ccqpein** [comment]
Yes, that’s what I do for now. Just would be more clear if the shell-maker-transcript-default-path has its own alias in chatgpt-shell.

**Comment by ccqpein** [comment]
Just minor suggestion. no need to change.
