### ISSUE TITLE
[FR] When `clear` gets sent, save the conversation

### ISSUE THREAD

**Issue by adham-omran** [xenodium/chatgpt-shell#22]
This enables a history just like ChatGPT
- [ ] The command `clear` writes the buffers content to a file
- [ ] The filename uses the first prompt to name it
- [ ] Moonshot: Use the API to summarize the first prompt to generate the name (e.g. Summarize in a title the conversation that starts with [PROMPT]), this is toggled with a variable (`chatgpt--create-title-on-save)`
- [x] Moonshot: Resume old conversations

**Comment by xenodium** [comment]
Thanks for filing.

> The command clear writes the buffers content to a file

I'm wondering if there are other shells that implement this pattern? If not, perhaps we can add a new command "save" for this purpose?

**Comment by xenodium** [comment]
> The command clear writes the buffers content to a file

Ok, haven't added this exact behaviour, but users can now invoke `chatgpt-shell-save-session-transcript` to save transcript to a file now.

In case clear is invoked inadvertenly, undo can always get the content back.

> Moonshot: Resume old conversations

If you save with `chatgpt-shell-save-session-transcript`, you can now use `chatgpt-shell-restore-session-from-transcript` to resume.
