### ISSUE TITLE
Deprecated models like gpt-4-vision-preview should be replaced by gpt-4o

### ISSUE THREAD

**Issue by casch-at** [xenodium/chatgpt-shell#220]
https://platform.openai.com/docs/deprecations/deprecation-history

**Comment by xenodium** [comment]
Thanks for filling! Are you keen on contributing a patch?

**Comment by xenodium** [comment]
Took a look. Fixed by f7b1f1e4b8a07c97deba92d9a23145d192ce715f. Please try it out and see if that works for ya. Please reopen if otherwise.
