### ISSUE TITLE
pcsv-read-quoting: Invalid read syntax: "Expected `\"' but got `T'"

### ISSUE THREAD

**Issue by rpoisel** [xenodium/chatgpt-shell#221]
**Summary:**
Executing `chatgpt-shell-load-awesome-prompts` results in an error, as described in the title of this issue.

**Description:**
This issue appears to be due to an issue with the dependent repository [f/awesome-chatgpt-prompts](https://github.com/f/awesome-chatgpt-prompts).

**Related Pull Request:**
There is already a pull request addressing this issue in the dependent repository: [f/awesome-chatgpt-prompts/pull/758](https://github.com/f/awesome-chatgpt-prompts/pull/758).

**Workaround:**
As a temporary solution, you can change the URL of the awesome prompts CSV file to the following in the `chatgpt-shell.el` file within your Emacs installation:

```elisp
https://raw.githubusercontent.com/TFWol/awesome-chatgpt-prompts/patch-1/prompts.csv
```

**Comment by xenodium** [comment]
Thanks for filing and providing a workaround! We can keep this issue open with the workaround for anyone keen to solve in the immediate term (locally).

**Comment by xenodium** [comment]
btw (unrelated), do you have any favorite or frequent prompt that you use from awesome prompts? I had kinda forgotten about them.

**Comment by rpoisel** [comment]
> Thanks for filing and providing a workaround! We can keep this issue open with the workaround for anyone keen to solve in the immediate term (locally).

Sure, thx too for this great package!

> btw (unrelated), do you have any favorite or frequent prompt that you use from awesome prompts? I had kinda forgotten about them.

Well, yes, I use the `Positive Programming` prompt quite often. It results in concise answers and positive vibes. :grinning:

**Comment by xenodium** [comment]
I'll have to check it out :)

**Comment by xenodium** [comment]
Looks like loading is no longer an issue. Gonna close this issue. Please reopen if otherwise.
