### ISSUE TITLE
Why does a chatgpt-shell buffer pop up when I launch Emacs?

### ISSUE THREAD

**Issue by madorian** [xenodium/chatgpt-shell#223]
I don't want a pop up buffer when I launch Emacs.

Can I somehow kill that?;)

**Comment by xenodium** [comment]
That shouldn't happen. Can you share your package setup?

**Comment by madorian** [comment]
Here's my init
```
(use-package shell-maker
  :straight (:host github :repo "xenodium/chatgpt-shell" :files ("shell-maker.el")))

(use-package chatgpt-shell
  :requires shell-maker
  :straight (:host github :repo "xenodium/chatgpt-shell" :files ("chatgpt-shell.el")))

(setq chatgpt-shell-openai-key "foo")

(use-package ob-chatgpt-shell
  :requires shell-maker
  :straight (:host github :repo "xenodium/chatgpt-shell" :files ("ob-chatgpt-shell.el")))

(setq chatgpt-shell-streaming nil)

(require 'ob-chatgpt-shell)
(ob-chatgpt-shell-setup)
(add-to-list 'org-structure-template-alist '("sg" . "src chatgpt-shell\n"))
```

**Comment by xenodium** [comment]
Looks ok to me. I'm loading with very similar code and I'm not seeing the behaviour you're describing. Any chance you have code elsewhere? Can you launch Emacs with -Q and only execute the above snippet? Does it still reproduce the issue? Do you have a video showing the issue?

ps. On a minor note, I'd probably move things like `(setq chatgpt-shell-streaming nil)` to the `chatgpt-shell` `use-package` `:config` block. Same for `ob-chatgpt-shell` `:config`.

**Comment by madorian** [comment]
Sorry, figured it out. I cleaned up the file and found some weird fragments. All good now, thanks;)
