### ISSUE TITLE
[FR] Ability to Extract a Single Response to External Buffer with Custom Name

### ISSUE THREAD

**Issue by adham-omran** [xenodium/chatgpt-shell#23]
- [x] Add a new function that allows users to extract a single response to an external buffer with a custom name that can be preset on entered with a prompt.

Use case: I find this useful to dissect a response into separate questions and answers for creating Anki cards.

**Comment by xenodium** [comment]
The new `chatgpt-shell-view-current` opens current entry in a separate buffer, which gives almost what you described. Can use `M-x rename` on it. Or if still keen on all in one go, something like the following would do it:

```emacs lisp
(defun my/chatgpt-shell-view-current-as ()
  "Like `chatgpt-shell-view-current' but prompts for a buffer name"
  (interactive)
  (chatgpt-shell-view-current)
  (let ((name (string-trim (read-string "Name: "))))
    (unless (string-empty-p name)
      (rename-buffer (read-string "Name: ")))))
```
