### ISSUE TITLE
Yasnippet support

### ISSUE THREAD

**Issue by vxe** [xenodium/chatgpt-shell#233]
It seems like support was added here: https://github.com/xenodium/chatgpt-shell/issues/114

However my snippets which are created in the chatgpt-shell directory as shown above are failing to expand with

```
helm-M-x-execute-command: [yas] ‘yas-expand-snippet’ needs properly setup ‘yas-minor-mode’
```

is there any additional configuration to get this behaviour? thanks

**Comment by xenodium** [comment]
Hi there. Sounds more like a yasnippet misconfig issue, though I'd need more details to be able to help out. 

If I'm understading correctly, you'd like to expand yasnippets in the shell buffer. Correct?

1. Can you share the yasnippet you're expanding?
2. Can you show the directory where the snippet is stored?
3. Are you enabling yas-minor-mode in the shell?

**Comment by vxe** [comment]
running  `(yas-global-mode)` seems to have fixed it, closing

**Comment by xenodium** [comment]
Glad to hear it's now sorted. If you're finding chatgpt-shell useful, please consider [supporting](https://github.com/sponsors/xenodium) so I can make this project self-sustainable and continue to improve and providing support.
