### ISSUE TITLE
Must switch buffer to actually get the result (some times)

### ISSUE THREAD

**Issue by konrad1977** [xenodium/chatgpt-shell#238]
Sometimes it works, other it doesn't. 
There are some messages in *messages* that might help.

https://github.com/user-attachments/assets/fb5a4ec5-7623-404a-9946-1658444c9443

**Comment by konrad1977** [comment]
I think it could have to do with auto-revert modes maybe?

**Comment by xenodium** [comment]
Did you figure something out? Mind sharing, in case someone else runs into it?

**Comment by konrad1977** [comment]
This works much better now in the latest version (updated today). Its way faster also, well done!

**Comment by xenodium** [comment]
Great to hear!
