### ISSUE TITLE
Version 1.17.1 quick-insert doesnt work

### ISSUE THREAD

**Issue by konrad1977** [xenodium/chatgpt-shell#239]
When I select a region and quick-insert. I only get this:
chatgpt-shell-post-chatgpt-messages: Keyword argument :on-finished not one of (:messages :version :other-params :on-output :on-success :on-failure :temperature :streaming)

Then nothing happens.

**Comment by xenodium** [comment]
Thanks for reporting. Can you update shell-maker too and see if the problem persists?

**Comment by xenodium** [comment]
Nevermind. Fixing...

**Comment by xenodium** [comment]
Ok, try v1.18.1. Lemme know how if that solves it for ya.

ps. Thank you for the sponsorship. Much appreciated!

**Comment by konrad1977** [comment]
You're welcome, not much it will get you a beer or two. Small price for something that turns my favorite editor into something like cursor.

**Comment by konrad1977** [comment]
The modify works, but the new insert (no region) isn't working great. It inserts ob- tags instead of writing the code like the previous insert did. Am I missing something?

**Comment by xenodium** [comment]
On the move now. I'll take a look later today.

**Comment by xenodium** [comment]
> The modify works, but the new insert (no region) isn't working great. It inserts ob- tags instead of writing the code like the previous insert did. Am I missing something?

Should be good from v1.19.1. Lemme know if otherwise.

**Comment by xenodium** [comment]
> You're welcome, not much it will get you a beer or two. Small price for something that turns my favorite editor into something like cursor.

I've been doing quite bit to rework things, tidy up, make it more extensible, etc. I'd like to make this effort more sustainable. All sponsorships super welcome.

By the way, try the compose interface. I've grown fond of it:

1. Select a region.
2. M-x chatgpt-shell-prompt-compose (I have it bound to `C-c C-e`.

Finalize query and `C-c C-c` (magit style).

Post submission, you will have additional commands (single character bindings). n/p/TAB navigation, r = reply, etc. Would love to hear your experience. Check the mode help for all bindings.

ps. I'd like to make everything multi-modal too... I know you're keen on Claude ;)

**Comment by konrad1977** [comment]
Work like a charm now. Many thanks!

**Comment by xenodium** [comment]
Yay. Great to hear.
