### ISSUE TITLE
shell-maker-submit: Symbol’s function definition is void: closurep

### ISSUE THREAD

**Issue by unhandyandy** [xenodium/chatgpt-shell#248]
I get the error

shell-maker-submit: Symbol’s function definition is void: closurep

whenever I hit return.  Do I have to reinstall shell-maker?

**Comment by xenodium** [comment]
Looks like closurep snuck in and it's on Emacs 30. What Emacs version are you on? Does installing https://elpa.gnu.org/packages/compat.html sort it out for you?

**Comment by unhandyandy** [comment]
I'm on emacs 29.4, and installing compat worked, thanks!

**Comment by xenodium** [comment]
Removed it anyway https://github.com/xenodium/shell-maker/commit/e39ae5fd010d4c5aa6ce6db4ea3eecb68cae6073
