### ISSUE TITLE
testing gemini issue with openai key required

### ISSUE THREAD

**Issue by oatmealm** [xenodium/chatgpt-shell#249]
I have chatgpt-shell-google-key set with the key.
I don't know hot to make gemini the default.
When I try to swap to gemini model, I'm seeing:

```
Gemini(1.5-pro-latest/General)> Hello!

Variable `chatgpt-shell-openai-key' needs to be set to your key.

Try M-x set-variable chatgpt-shell-openai-key
```

I had to set it to some random string and it seems next time I invoke chatgpt-shll, it default to gemini and doesn't complain about openai key...

How can I set this behavior to be the default?

**Comment by xenodium** [comment]
> I don't know hot to make gemini the default.

(setq chatgpt-shell-model-version "gemini-1.5-pro-latest")

> When I try to swap to gemini model, I'm seeing:
>
> Variable `chatgpt-shell-openai-key' needs to be set to your key.

Ah, lemme fix that. Should be smarter here.

**Comment by xenodium** [comment]
https://github.com/xenodium/chatgpt-shell/commit/093c490bc8a550858f7eef87c0ad2cca64b1a772 should fix it. Lemme know if that doesn't fix it for you.

You'll need version 2.0.4. 

For changes to take effect, you'd have to force eval chatgpt-shell--config in chatgpt-shell.el and M-x chatgpt-shell-reload-models. Or just restart Emacs.

**Comment by oatmealm** [comment]
Thanks. I'll take a look asap. 
 I see that I can list more than one Gemini model. How do I swap between models in a particular list for a provider? Ie. Change back and forth from flash to pro?

**Comment by xenodium** [comment]
`M-x chatgpt-shell-swap-model` for swapping any mode. I've only loaded pro for the time being. Happy to take contributions if you'd like to help populate it? https://github.com/xenodium/chatgpt-shell/blob/da8d9e7eb686e86430196c87f1899c042d61a153/chatgpt-shell-google.el#L45

**Comment by oatmealm** [comment]
Wouldn't it be easier to make it user configurable? I see the same issue with the ollama addition (much appreciated, great addition) base url.

**Comment by xenodium** [comment]
> Wouldn't it be easier to make it user configurable? 

Is customizing via `chatgpt-shell-models` enough?

**Comment by oatmealm** [comment]
I'm sort of used to the way I'm using `gptel`, `ellama` etc where you can simply provide one configuration as default, and then a list of additional models to be able to activate as needed.

```
  ;; (gptel-make-gemini
  ;;     "gemini"
  ;;   :key (password-store-get "api/gemini")
  ;;   :stream t
  ;;   :models '("gemini-1.5-flash" "gemini-1.5-pro"))
```

The struct for `chatgpt-shell-models` seems rather intimidating... hopefully most of the values can have defaults I don't have to set unless I need to?

```
 ((:version . "gemini-1.5-pro-latest")
  (:short-version . "1.5-pro-latest")
  (:label . "Gemini")
  (:provider . "Google")
  (:path . "/v1beta/models/gemini-1.5-pro-latest")
  (:token-width . 4)
  (:context-window . 2097152)
  (:url-base . chatgpt-shell-google-api-url-base)
  (:handler . chatgpt-shell-google--handle-gemini-command)
  (:filter . chatgpt-shell-google--extract-gemini-response)
  (:payload . chatgpt-shell-google--make-payload)
  (:url . chatgpt-shell-google--make-url)
  (:headers . chatgpt-shell-google--make-headers)
  (:key . chatgpt-shell-google-key)
  (:validate-command . chatgpt-shell-google--validate-command))
```

I was also confused by the fact that `chatgpt-shell-google-models` is a function... is it meant to eventually build a list via some sort of discovry or simply return a fixed list?

**Comment by xenodium** [comment]
> I'm sort of used to the way I'm using gptel, ellama etc where you can simply provide one configuration as default, and then a list of additional models to be able to activate as needed.

You can do this by setting `chatgpt-shell-models`.

>  The struct for chatgpt-shell-models seems rather intimidating... hopefully most of the values can have defaults I don't have to set unless I need to?

Agree. Sorry. Had been meaning to add a convenience helper. Now added in: https://github.com/xenodium/chatgpt-shell/commit/b0a13679a77a27a87d369fa8c41af1e271d48501

If you only want one model available in your config, you could do:

```
(setq chatgpt-shell-models
      (list (chatgpt-shell-google-make-model :version "gemini-1.5-flash"
                                             :short-version "1.5-flash"
                                             :path "/v1beta/models/gemini-1.5-flash"
                                             :token-width 4
                                             :context-window 2097152)))
```

> I was also confused by the fact that chatgpt-shell-google-models is a function... 

`chatgpt-shell-models` is the main entry point for setting models. I can look into changing this, but it's been pretty useful to reset models via `M-x chatgpt-shell-reload-default-models`.

Hope this helps.

**Comment by xenodium** [comment]
ps. v2.0.8 includes gemini-1.5-flash

**Comment by oatmealm** [comment]
Will try this asap.
