### ISSUE TITLE
Linux vs. Win

### ISSUE THREAD

**Issue by unhandyandy** [xenodium/chatgpt-shell#251]
When I do C-c C-v <tab> I see:
on Linux only OpenAI models;
on Win OpenAI, Google, and other models.

Why the difference?  What do I have to do access Google Gemini from Linux?

**Comment by xenodium** [comment]
Do you have an older version installed on Linux? You need v2 and up.

`M-x chatgpt-shell-version` shows you what version you have

**Comment by unhandyandy** [comment]
I installed Melpa 20241121.2230, but the version command returns v1.25.1.  Do I need to clone the git repo to update it on Linux?

**Comment by xenodium** [comment]
Sounds like it was installed from MELPA stable? https://stable.melpa.org/#/chatgpt-shell

Install from MELPA https://melpa.org/#/chatgpt-shell

I'll soon bump stable too after multi-model gets a little usage.

**Comment by unhandyandy** [comment]
No, I think 20241121.2230 was from melpa.  When I just tried to reinstall it I got:

package--with-response-buffer-1: https://melpa.org/packages/chatgpt-shell-20241121.2230.tar: Not found

**Comment by unhandyandy** [comment]
Ah, I see, I didn't realize I had to restart emacs after installing a different version.
Thanks.
