### ISSUE TITLE
[Feature request] Use Ollama list-local-models API call to list locally installed models

### ISSUE THREAD

**Issue by sivaramn** [xenodium/chatgpt-shell#253]
Ollama has [https://github.com/ollama/ollama/blob/main/docs/api.md#list-local-models](url) that returns a JSON payload of installed models.  this can be parsed to get the model names to automatically fill in the model list.  Additionally,  [https://github.com/ollama/ollama/blob/main/docs/api.md#show-model-information](url) can also be parsed to get parameters which may be different from the defaults assumed.

**Comment by djr7C4** [comment]
@xenodium Would you be interested in a pull request to implement this? It's a feature I'd like to see added.

**Comment by xenodium** [comment]
Certainly! What I had in mind was to add a couple of functions:

# chatgpt-shell-ollama--fetch-models

```
(defun chatgpt-shell-ollama--fetch-models ()
 ;; Make http request (maybe use) and return  a list of models built with `chatgpt-shell-ollama-make-model`.
)
```

# chatgpt-shell-ollama-load-models

```
(defun chatgpt-shell-ollama-load-models ()
  (interactive)
  ;; Use chatgpt-shell-ollama--fetch-models to fetch and set chatgpt-shell-models.
  ;;   maybe use (shell-maker-make-http-request :async nil)
  ;; Bonus, add missing models only to chatgpt-shell-models.
)
```

We can maybe start with something like that and see how it feels? What do you think?

**Comment by djr7C4** [comment]
That seems sensible. I would make it so chatgpt-shell-ollama-load-models
only loads models that are present locally since missing models will simply
result in errors.

**Comment by xenodium** [comment]
> I would make it so chatgpt-shell-ollama-load-models
only loads models that are present locally since missing models will simply
result in errors.

Keep in mind this would also override non-ollama models too, so ChatGPT, Claude, and Gemini would be removed from the default models. That may be OK. We can try it as see how it goes.

**Comment by djr7C4** [comment]
Why not simply replace the current implementation of
chatgpt-shell-ollama-models instead of adding
chatgpt-shell-ollama-load-models? That seems simpler and would also avoid
this problem. If startup latency is a concern, it could be made
configurable by the user as to which implementation to use.

**Comment by xenodium** [comment]
> If startup latency is a concern

Yep. That's the main thing. This would affect non-ollama users too. So for example, an OpenAI user would now have to disable Ollama features (unrelated) to speed up their setup.

> it could be made configurable by the user as to which implementation to use

If we want to keep the feature relevant to the target audience (Ollama users), they could also invoke chatgpt-shell-ollama-load-models from their use-package :config block (or preferred equivalent).

**Comment by djr7C4** [comment]
I see your point. My issue is that I would like to avoid having models in the list that do not actually exist on the system since they will not work if selected. Therefore, I would want to clear out the existing ollama models first before running chatgpt-shell-ollama-load-models. Maybe there should be a chatgpt-shell-ollama-clear-models command to facilitate this use case.

**Comment by xenodium** [comment]
If we go with the plan of allowing the load function to override the models list (maybe add an optional :override param), it can achieve the user experience you're describing?

The config would look as follows:

```
(use-package chatgpt-shell
  :config 
  (chatgpt-shell-ollama-load-models :override t))
```

**Comment by djr7C4** [comment]
Sure, that seems reasonable.

**Comment by xenodium** [comment]
Huge thanks to @djr7C4! This is now implemented in https://github.com/xenodium/chatgpt-shell/pull/262

If you want to invoke manually, use:

`M-x chatgpt-shell-ollama-load-models`

Subsequently swap models as usual:

`M-x chatgpt-shell-swap-model`

If you want to invoke programatically, use:

## Merge existing models

(use-package chatgpt-shell
  :config
  (chatgpt-shell-ollama-load-models))

## Replace existing models

(use-package chatgpt-shell
  :config
  (chatgpt-shell-ollama-load-models :override t))
