### ISSUE TITLE
unable to auth with gpt-4o model

### ISSUE THREAD

**Issue by andrewmslack** [xenodium/chatgpt-shell#254]
```
curl: (22) The requested URL returned error: 401Authentication Error, API Key not allowed to access model. 
This token can only access models=['gpt-4o']. Tried to access chatgpt-4o-latest
```
The proxy that I talk to only permits `gpt-4o` model though the shell is using `chatgpt-4o-latest`

Is there some variable(s) I can use to set the model I use. 

Thanks

**Comment by xenodium** [comment]
Gonna close. gpt-4o seems to be working now that it's been added to models list. Please reopen if otherwise.
