### ISSUE TITLE
value: 'messages[0].role' does not support 'system' with this model.

### ISSUE THREAD

**Issue by gnusupport** [xenodium/chatgpt-shell#256]
curl: (22) The requested URL returned error: 400Unsupported value: 'messages[0].role' does not support 'system' with this model.

I just pulled latest and in shell it does not work with 01-mini

This below however works,
```
	 (response (cond (model (chatgpt-shell-post :context (list (cons prompt nil)) :version model))
			 (t (error "Could not find a model.  Missing model setup?")))))
```

**Comment by xenodium** [comment]
> does not support 'system' with this model.

OpenAI model returned an error because the model chosen does not support system prompts.

Remove the system prompt from the query.

If using via shell access, `M-x chatgpt-shell-swap-system-prompt` and select None.
