### ISSUE TITLE
Redirecting curl error stream to /dev/null doesn't work on windows

### ISSUE THREAD

**Issue by MunsterPlop** [xenodium/chatgpt-shell#26]
Redirecting the error stream to `/dev/null` doesn't work on windows.
Redirecting to `NUL` should be good I think.
I made a pull request with a suggested fix.

Please let me know if it looks fine :).

**Comment by xenodium** [comment]
I don't have a Windows machine, so I'll assume this works for you now :)

**Comment by MunsterPlop** [comment]
It works just fine now, thank you for merging!
