### ISSUE TITLE
Setting variable chatgpt-shell-model-version after you've started a shell doesnt do anything

### ISSUE THREAD

**Issue by ryanobjc** [xenodium/chatgpt-shell#260]
Start a chatgpt-shell, but then decide that openai is not good enough, so set the chatgpt-shell-model-version to something better, and now future chatgpt-shells won't respect the variable.

**Comment by ryanobjc** [comment]
Seems like there is some caching somewhere

**Comment by xenodium** [comment]
> so set the chatgpt-shell-model-version to something better

I'm guessing you're doing this via (setq chatgpt-shell-model-version ...)? Keep in mind `chatgpt-shell-model-version` becomes buffer-local for each shell instance, so you can run mutiple shells of different versions simultaneously (you can create multiple shells via C-u chatgpt-shell).

If you swap via `M-x chatgpt-shell-swap-model`, it should do the right thing for you (please let me know if it isn't).

If still keen you use setq, you may need to do

```
(setq-local chatgpt-shell-model-version ...) ;; when changing for current shell buffer.
(setq-default chatgpt-shell-model-version ...) ;; for changing for future shells.
```

**Comment by ryanobjc** [comment]
So right you are, thanks for the quick update!

Right after I had made this issue, my model did get a refresh and update.  I think you got it spot on.

As a side note I do like that you are retrieving the api key on a regular basis, and not overly caching it.  I have found api key caching has been a thorn in my side with other packages.

**Comment by xenodium** [comment]
Glad to hear! If you're finding the package useful, consider [sponsoring](https://github.com/sponsors/xenodium).
