### ISSUE TITLE
curl error when swapping to o1-preview

### ISSUE THREAD

**Issue by mikaelspringer** [xenodium/chatgpt-shell#261]
When I swap model from 4o to o1-preview I get a curl error as can be seen below;
```
Welcome to ChatGPT shell

  Type help and press RET for details.

  Like this package? Consider ✨sponsoring✨


ChatGPT(chatgpt-4o-latest/Programming)> who made you?
I was created by OpenAI.

ChatGPT(chatgpt-4o-latest/Programming)> 

ChatGPT(o1-preview/Programming)> who made you?

curl: (22) The requested URL returned error: 400Unsupported value: 'messages[0].role' does not support 'system' with this model.


ChatGPT(o1-preview/Programming)> 
```
My configuration looks like this;
```
(use-package chatgpt-shell
  :ensure t
  :bind
  (:map global-map
	("s-i c" . chatgpt-shell)
	("s-i x" . chatgpt-shell-explain-code))
  :custom
  (chatgpt-shell-openai-key 'ms-get-openai-api-key)
  ;; gpt-4o.
  (chatgpt-shell-model-version 0)
  (chatgpt-shell-system-prompt 2))

```

**Comment by xenodium** [comment]
Have look at https://github.com/xenodium/chatgpt-shell/issues/256#issuecomment-2501609341

I'll see if I can introduce additional validation to provide a friendlier error which tells one how to fix it.

**Comment by xenodium** [comment]
Ok. Added in https://github.com/xenodium/chatgpt-shell/commit/22d4edcb94722aa90db5041fa6be3cc1224fabf6

<img width="741" alt="Screenshot 2024-11-28 at 10 40 52" src="https://github.com/user-attachments/assets/2192d0ed-e1f5-4610-b99b-848b161283f7">

**Comment by xenodium** [comment]
Gonna close this. Please reopen if ya reckon there's something else to add.
