### ISSUE TITLE
the lloama interface seems not to work

### ISSUE THREAD

**Issue by ouboub** [xenodium/chatgpt-shell#265]
Hi
on Ubuntu 24.04 I downloaded and install ollama via
<https://ollama.com/download>
I also put in my init file

```emacs-lisp
(setq chatgpt-shell-model-version "llama3.2")

(setq chatgpt-shell-openai-key
      (auth-source-pick-first-password :host "api.openai.com"))
```
then I run `chatgpt-shell`

And tried a request, the result was

```
<shell-maker-failed-command>
Ollama(llama3.2/General)> please translate into spanish: hi how are you
<shell-maker-end-of-prompt>

curl: (22) The requested URL returned error: 404

<shell-maker-failed-command>
Ollama(llama3.2/General)> 
```

What could be the problem, sigh

**Comment by xenodium** [comment]
Looks like llama3.2 is missing from the Ollama installation.

What Ollama models do you have installed?

From command-line, you can do something like:

`ollama list`

You can install llama3.2 with something like:

`ollama pull llama3.2`

You should be able to ask something in the shell at this point.

If you want to get chatgpt-shell to sync up with other ollama available/downloaded models, you can invoke `M-x chatgpt-shell-ollama-load-models`.

You can subsequently swap the active model from your shell at any time using `M-x chatgpt-shell-swap-system-prompt`

**Comment by ouboub** [comment]
> 
> `ollama pull llama3.2`
> 

Ha, I thougt this was installed automatically. So I did what you recommended, restarted emacs, and VOILA it works, a bit different and maybe slower that via the web interface, but that cannot be helped.

Thanks very very much. I will check out later, how to buy you a coffee 😉

**Comment by xenodium** [comment]
> Ha, I thougt this was installed automatically. So I did what you recommended, restarted emacs, and VOILA it works,

yay! 🎉🎉

> I will check out later, how to buy you a coffee 😉

https://github.com/sponsors/xenodium 😅

**Comment by xenodium** [comment]
> maybe slower that via the web interface, but that cannot be helped.

FYI looks like you get some free access on Gemini https://fedia.social/notes/a1e9pvimjbemfn2w

**Comment by ouboub** [comment]
> FYI looks like you get some free access on Gemini
> https://fedia.social/notes/a1e9pvimjbemfn2w
> 

Thanks, but this link show a page in German (which you also  speak I understand) but there is no link to Gemini
what do I miss (I do speak German)

**Comment by xenodium** [comment]
You mentioned:

> a bit different and maybe slower that via the web interface, but that cannot be helped.

Just letting you know Gemini is free to a point (if this is of interest) as reported by user:

<img width="658" alt="image" src="https://github.com/user-attachments/assets/c953c3b9-2aef-4707-be53-8bc393211854">

ps. I don't speak German :) But there's a handy translate button on Mastodon.
