### ISSUE TITLE
Support for using ChatGPT through HTTP(S) proxy

### ISSUE THREAD

**Issue by farrellm** [xenodium/chatgpt-shell#267]
Support for using ChatGPT through HTTP(S) proxy seems to have been lost with the move to `shell-maker`. Can you add it back please?

If you search for `chatgpt-shell-additional-curl-options`, the only hit is in the readme.

**Comment by xenodium** [comment]
Ah yes. With the  multi-model restructure and removing the direct dependency on curl (possibly add native fetching in the future), this feature was lost. I need to see how to re-introduce in a curl-agnostic way in chatgpt-shell or perhaps expose the curl option via shell-maker.

Do you just need the --proxy option?

**Comment by farrellm** [comment]
Yes, I just need the --proxy option

**Comment by xenodium** [comment]
I've added chatgpt-shell-proxy, which gets added as the value for --proxy. I don't have a proxy to test with. Can you give it a try please?

You'll need:

shell-maker v0.75.1
chatgpt-shell v2.7.1

**Comment by farrellm** [comment]
Thank you for this. However, with `chatgpt-shell` and `chatgpt-shell-prompt-compose`, I still do not see the proxy being used. I think `:proxy chatgpt-shell-proxy` needs to be added to the request call in `chatgpt-shell-openai--handle-chatgpt-command`? When I add that it works.

**Comment by xenodium** [comment]
> needs to be added to the request call in chatgpt-shell-openai--handle-chatgpt-command?

Definitely. Thank you. I missed that one. Added in https://github.com/xenodium/chatgpt-shell/commit/591457bce5fdbbe7caaec7b0585e09e2be327269.

**Comment by xenodium** [comment]
Btw, nice to see someone using the compose interface. It's my preferred mechanism, but I think it's not super well know. How is it working for you?

**Comment by farrellm** [comment]
I’ve only used it a few times, but so far I like it a lot. Every time it has produced exactly the edit I wanted. So far, it is my preferred mechanism as well. 

Proxy support is working perfectly for me now, so I’ll close this issue, though I’d note that the other model providers probably need the same change.

**Comment by xenodium** [comment]
> I’ve only used it a few times, but so far I like it a lot. Every time it has produced exactly the edit I wanted. So far, it is my preferred mechanism as well.

Nice to hear. I've been meaning to add a transient menu to make the follow-up commands more discoverable (r, m, e, n/p, etc)

> though I’d note that the other model providers probably need the same change.

I think I covered those in the initial change, but I'll double check. Thanks.
