### ISSUE TITLE
(setq chatgpt-shell-model-version) does not set the default model

### ISSUE THREAD

**Issue by dbug13** [xenodium/chatgpt-shell#269]
Expected behavior:
(setq chatgpt-shell-model-version "gemini-1.5-flash")
then run M-x chatgpt-shell
should set the default model to **gemini-1.5-flash** and prompt should show:
Gemini(1.5-flash/General)> 

Actual behavor:
(setq chatgpt-shell-model-version "gemini-1.5-flash")
then run M-x chatgpt-shell
Result: model used is **gemini-1.5-pro-latest**  and prompt shows:
Gemini(1.5-pro-latest/General)>

**Comment by dbug13** [comment]
This was user error:

I was setting the value in the :custom section of my use-package call:
(use-package chatgpt-shell
  :custom
  (setq chatgpt-shell-model-version "gemini-1.5-flash")
 ...

I moved the setting to the :config section and now the default model is being set as expected:
(use-package chatgpt-shell
  :config
  (setq chatgpt-shell-model-version "gemini-1.5-flash")
  :custom
 ...

**Comment by xenodium** [comment]
> :custom
> (setq chatgpt-shell-model-version "gemini-1.5-flash")

You can still use :custom. Just remember the syntax is a little different (no setq):

```
:custom
  (chatgpt-shell-model-version "gemini-1.5-flash")
```
