### ISSUE TITLE
Different way of getting authinfo secret?

### ISSUE THREAD

**Issue by MunsterPlop** [xenodium/chatgpt-shell#27]
In the readme, there is this example:

```elisp
;; or if using auth-sources, e.g., so the file ~/.authinfo has this line:
;;  machine openai.com password OPENAI_KEY
(setq chatgpt-shell-openai-key
      (plist-get (car (auth-source-search :host "openai.com"))
                 :secret))
```

I was wondering about the difference between this and the simpler:
```elisp
(setq chatgpt-shell-openai-key (auth-source-pick-first-password :host "openai.com"))
```
that I see used in other packages.

Evaluating the readme example, I get a byte code function object where the secret is obfuscated and with `auth-source-pick-first-password`, a simple clear string.
I suppose that means the readme example is more secure and those other packages are not?

It's more of a question than an actual issue but I needed to know if I was correct.

**Comment by MunsterPlop** [comment]
I checked the implementation for `auth-source-pick-first-password`:

```elisp
(defun auth-source-pick-first-password (&rest spec)
  "Pick the first secret found from applying SPEC to `auth-source-search'."
  (let* ((result (nth 0 (apply #'auth-source-search (plist-put spec :max 1))))
         (secret (plist-get result :secret)))

    (if (functionp secret)
        (funcall secret)
      secret)))
```

and from what I see, it should be a valid substitute unless anyone has an objection.

**Comment by xenodium** [comment]
Given #31 discussion, I think we can close this one. Please lemme know if otherwise.
