### ISSUE TITLE
[Feature request] Make the behavior of scrolling to the end of response when finished configurable

### ISSUE THREAD

**Issue by mpereira** [xenodium/chatgpt-shell#279]
There are two automatic scrolling behaviors that currently happen in chatgpt-shell:

1. When the LLM provider finishes streaming a response, the window will be automatically scrolled to the end.
2. If the point is at the bottom of the window, when the LLM provider starts streaming a response the window will automatically scroll as new chunks arrive.
   
This feature request is mostly about making 1 configurable. But it would be nice if 2 was also configurable.

This feature request was created from https://github.com/xenodium/chatgpt-shell/issues/119#issuecomment-2557392124.

**Comment by xenodium** [comment]
Sorry for the delay. If you update shell-maket to v0.76.2, 1. shouldn't happen anymore. I may add some configuration to bring it back in.

Haven't done anything about 2. just yet.

**Comment by mpereira** [comment]
Just tested 1. here, thanks Álvaro!

**Comment by xenodium** [comment]
Yay! and thank you for sponsoring! 🎉

**Comment by mpereira** [comment]
By the way, 1. was more important to me than 2., so feel free to close this issue.
