### ISSUE TITLE
Timeout issues, 30 seconds is not enough.

### ISSUE THREAD

**Issue by arael** [xenodium/chatgpt-shell#28]
Thank you very much for developing ChatGPT shell for Emacs.

May I suggest to externalize the timeout in a variable? 30 seconds often results in timeouts when the requests are complex.

I have now increased the time to 60 seconds by modifying the value of the -m parameter passed to curl. But there is probably a saner way to do this directly from Emacs.

**Comment by xenodium** [comment]
> Thank you very much for developing ChatGPT shell for Emacs.

Glad you like it!

> May I suggest to externalize the timeout in a variable? 30 seconds often results in timeouts when the requests are complex.

Good call. Let's increase to 60 and also expose a custom variable. 

If you're keen to send a PR, that'd be great. Otherwise, I'll give it a go when a have a chance.

**Comment by mcraveiro** [comment]
Excellent news, been hitting this timeout limit a lot! :-) updating to latest! Thanks for the great work.
