### ISSUE TITLE
[Feature request] Make it possible to create indirect buffer from code block in prompt compose buffers

### ISSUE THREAD

**Issue by mpereira** [xenodium/chatgpt-shell#282]
Hi Álvaro,

I started using the prompt compose buffers more frequently at your suggestion, and they're great! Thanks.

One thing I commonly do in them is selecting and yanking entire code blocks. It would be nice to have something like `markdown-edit-code-block` from `markdown-mode` which creates an indirect buffer with the code block at point, but in prompt compose buffers. Read-only in this case.

What do you think?

**Comment by xenodium** [comment]
> I started using the prompt compose buffers more frequently at your suggestion, and they're great! Thanks.

Nice to hear!

> One thing I commonly do in them is selecting and yanking entire code blocks.

I'm guessing you already found invoking compose with an active region automatically copies the region over to the compose buffer?

> It would be nice to have something like markdown-edit-code-block from markdown-mode which creates an indirect buffer with the code block at point, but in prompt compose buffers. Read-only in this case.

If I'm understanding correctly, you want to edit code blocks found in the read-only compose buffer, using a separate buffer and respective language major mode? Is that so you can modify LLM responses? I started looking into something like this, but it needs more work as editing the compose buffer is not enough. I need to edit the shell history too.

Or do yuo mean something else? Maybe run me through entire flow?

**Comment by mpereira** [comment]
> > One thing I commonly do in them is selecting and yanking entire code blocks.
> 
> I'm guessing you already found invoking compose with an active region automatically copies the region over to the compose buffer?

Yes!

> > It would be nice to have something like markdown-edit-code-block from markdown-mode which creates an indirect buffer with the code block at point, but in prompt compose buffers. Read-only in this case.
> 
> If I'm understanding correctly, you want to edit code blocks found in the read-only compose buffer, using a separate buffer and respective language major mode? Is that so you can modify LLM responses? I started looking into something like this, but it needs more work as editing the compose buffer is not enough. I need to edit the shell history too.

 I think I didn't do a good job explaining the use-case. What I think would be cool is, in a prompt compose buffer with a code block, be able to kill (as in `kill-new`) the whole block at point, and/or be able to open a read-only indirect buffer with only the contents of the code block, with the indirect buffer having the same major mode as the code block.

**Comment by xenodium** [comment]
Ah. I think that's straightforward. I have some code that does that plus editing, but I'd have to remove the editing for now, which I think is what you want anyway (a dedicated ready-only buffer to view block at point). Correct?

Something like this?

![view-block](https://github.com/user-attachments/assets/2327ef58-d911-493d-a11b-150096a2ca39)

**Comment by mpereira** [comment]
Yes! To be honest, just being able to either:

1. select and/or kill the code block content
2. open an indirect buffer with the block content

would already be useful. I didn't really think of editing the code block.

Your gif shows 2., which is pretty cool!

**Comment by xenodium** [comment]
> 1. select and/or kill the code block content

This one is already easy. TAB/Shift-TAB or n/p cycles through code blocks and automatically selects them. You can copy as normal after that. Does that help?

**Comment by xenodium** [comment]
> This one is already easy. TAB/Shift-TAB or n/p cycles through code blocks and automatically selects them. 

![select](https://github.com/user-attachments/assets/29a038bd-a019-467b-ad1d-a4f119dc92eb)

**Comment by mpereira** [comment]
> > 1. select and/or kill the code block content
> 
> This one is already easy. TAB/Shift-TAB or n/p cycles through code blocks and automatically selects them. You can copy as normal after that. Does that help?

It does, thanks! I wasn't aware of it.

**Comment by xenodium** [comment]
https://github.com/xenodium/chatgpt-shell/commit/17828c3d2dbc0d3c672020f0b84f62a1a64dae5f (v2.10.1) adds `M-xchatgpt-shell-view-block-at-point` also bound to `v` in compose buffer when it's read-only.

**Comment by xenodium** [comment]
> Yes! Super handy, and very cool that it creates a code block fenced with the correct language.

Also, if you use this, it remembers where the snippet came from. With response snippets, you can press 'i' on them and it would attempt to insert merge it back where it came from. This is all super experimental though. May need more work to make it more robust.

**Comment by mpereira** [comment]
> [17828c3](https://github.com/xenodium/chatgpt-shell/commit/17828c3d2dbc0d3c672020f0b84f62a1a64dae5f) (v2.10.1) adds `M-xchatgpt-shell-view-block-at-point` also bound to `v` in compose buffer when it's read-only.

Just tried it out, works great!

Feel free to close this issue.

**Comment by mpereira** [comment]
> > Yes! Super handy, and very cool that it creates a code block fenced with the correct language.
> 
> Also, if you use this, it remembers where the snippet came from. With response snippets, you can press 'i' on them and it would attempt to insert merge it back where it came from. This is all super experimental though. May need more work to make it more robust.

One thing that I noticed is that, when I prompt compose a region from a buffer with modes like `eshell` or `prodigy-view` (from [prodigy.el](https://github.com/rejeep/prodigy.el)), the region will correctly be inserted into the prompt compose buffer, but `chatgpt-shell-prompt-compose-send-buffer` won't actually send the buffer. It will just hang there.

I can create a separate issue if you're able to reproduce.

**Comment by xenodium** [comment]
Yes please. File a bug. We can continue on there.

**Comment by xenodium** [comment]
> > > 1. select and/or kill the code block content
> > 
> > 
> > This one is already easy. TAB/Shift-TAB or n/p cycles through code blocks and automatically selects them. You can copy as normal after that. Does that help?
> 
> It does, thanks! I wasn't aware of it.

Btw, 2.12.1 compose now jumps to beginning of response too.
