### ISSUE TITLE
[Bug] 'q' keybinding from chatgpt-shell-view-block-at-point leaks into all emacs-lisp mode buffers

### ISSUE THREAD

**Issue by mpereira** [xenodium/chatgpt-shell#283]
> [17828c3](https://github.com/xenodium/chatgpt-shell/commit/17828c3d2dbc0d3c672020f0b84f62a1a64dae5f) (v2.10.1) adds `M-xchatgpt-shell-view-block-at-point` also bound to `v` in compose buffer when it's read-only.

After using prompt compose with an emacs lisp snippet region selected, all my emacs lisp buffers seem to have gotten a new mapping on "q" that would kill the buffer.

Checking `M-x describe-key` with `q` I saw:
```
q runs the command (closure ((edit-buffer . #<killed buffer>)) nil
(interactive) (quit-restore-window (get-buffer-window edit-buffer)
'kill)) (found in emacs-lisp-mode-map), which is an interactive Lisp
closure.

It is bound to q.

(anonymous)
```

Where `edit-buffer` looked like it could've been something added in the change to add `chatgpt-shell-view-block-at-point`.

I looked at the code and found the exact closure mapped to `q`:

https://github.com/xenodium/chatgpt-shell/blob/36f1094707b613225b031242de537fdecee31c6c/chatgpt-shell.el#L2839-L2843

Looking at `M-x describe-function local-set-key` says something which seems to be the root cause:
```
The binding goes in the current buffer's local map, which in most
cases is shared with all other buffers in the same major mode.
```

**Comment by xenodium** [comment]
oh my... yikes. sorry. Thanks for reporting. Looking at it.

**Comment by xenodium** [comment]
https://github.com/xenodium/chatgpt-shell/commit/ec58fa006bb9f45d262607cc08f45af341fb9a88 (v2.10.2) should fix it.

**Comment by mpereira** [comment]
> [ec58fa0](https://github.com/xenodium/chatgpt-shell/commit/ec58fa006bb9f45d262607cc08f45af341fb9a88) (v2.10.2) should fix it.

Upgraded, thank you!

**Comment by xenodium** [comment]
👍 Please report back and close the issue if fixed.

**Comment by mpereira** [comment]
Issue is fixed.
