### ISSUE TITLE
[Bug] chatgpt-prompt-compose-send-buffer hangs when composing from eshell or prodigy-view regions

### ISSUE THREAD

**Issue by mpereira** [xenodium/chatgpt-shell#284]
When I prompt compose a region from a buffer with modes like eshell or prodigy-view (from [prodigy.el](https://github.com/rejeep/prodigy.el)), the region will correctly be inserted into the prompt compose buffer, but chatgpt-shell-prompt-compose-send-buffer won't actually send the buffer. It will just hang there.

**Comment by xenodium** [comment]
https://github.com/xenodium/chatgpt-shell/commit/995a37541310398a6d32999e2f5fdded1b362d13 should fix it (v2.10.3)

**Comment by mpereira** [comment]
Verified that it fixed it, thanks Álvaro!

**Comment by xenodium** [comment]
Nice to hear. Thanks for reporting back Murilo!
