### ISSUE TITLE
Download images to a specific directory?

### ISSUE THREAD

**Issue by danieljaouen** [xenodium/chatgpt-shell#29]
I am trying to figure out where the DALL-E images are saved to.  Can we specify a specific directory to download them to?

**Comment by xenodium** [comment]
At moment under tmp. We can make this configurable. Having said this, if you place the point on an image and press RET, it will open the original image into a buffer. You can save or move anywhere.

**Comment by danieljaouen** [comment]
That answers my question.  Thanks!
