### ISSUE TITLE
authinfo passphrase prompt stops emacs daemon from starting

### ISSUE THREAD

**Issue by MunsterPlop** [xenodium/chatgpt-shell#31]
Using this:

```elisp
(setq chatgpt-shell-openai-key
      (plist-get (car (auth-source-search :host "openai.com"))
                 :secret))
```

Will have emacs prompt for your gpg passphrase but it won't work when launching Emacs daemon in  the background.

I suggest setting `chatgpt-shell-openai-key` in `inferior-chatgpt-mode-hook`, like that it will only prompt you after invoking `chatgpt-shell`:

```elisp
(add-hook 'inferior-chatgpt-mode-hook
          (lambda ()
            (setq chatgpt-shell-openai-key
                  (plist-get (car (auth-source-search :host "api.openai.com"))
                             :secret))))
```

**Comment by xenodium** [comment]
I'm not using the snippet myself, but can it not be delayed with something like the following? It should only prompt you for password when you use the shell. 

```
(setq chatgpt-shell-openai-key (lambda ()
  (plist-get (car (auth-source-search :host "api.openai.com") :secret)))))
```

If you can validate this works, I'll update the README. Or if you can send a PR, greatly appreciated also :)

ps. Replying from mobile.

**Comment by MunsterPlop** [comment]
I just tried this and while it asks for the passphrase when you first send a request to chatgpt, it gives back an `error 400`.
I believe it is because curl is sending the resulting closure object as is somehow.
Using the hook, the expression gets evaluated to a byte code function object which seems to work fine.

**Comment by MunsterPlop** [comment]
My authinfo setup is pretty basic.

In my init file I have:

```elisp
(setq auth-sources (list (expand-file-name
                          "etc/authinfo.gpg"
                          user-emacs-directory)
                         (expand-file-name "~/.authinfo.gpg")))
```

and in my .emacs.d/etc/authinfo.gpg, I have:

```
machine openai.com password MY_API_KEY
```

I use `straight.el` to pull `chatgpt-shell` which I then configure like so:

```elisp
(require 'chatgpt-shell)

(add-hook 'inferior-chatgpt-mode-hook
          (lambda ()
            (setq chatgpt-shell-openai-key
                  (plist-get (car (auth-source-search :host "api.openai.com"))
                             :secret))))
```

in which case, my passphrase is being prompted when I `M-x chatgpt-shell` and `chatgpt-shell-openai-key` evaluates to this:

```elisp
#[0 "\301\242\203\f\0\301\242\302\300!!\207\302\300!\207"
    ["<my_obfuscated_api_key"
     (nil)
     auth-source--deobfuscate]
    3]
```

whereas if I use your snippet, my passphrase is being prompted when I first send something `ChatGPT> Hi` and `chatgpt-shell-openai-key` evaluates to:

```elisp
(closure
 (t)
 nil
 (plist-get
  (car
   (auth-source-search :host "openai.com")
   :secret)))
```

Apparently, by the time the curl request is formed, the byte code function ends up returning the clear key (which works) whereas the closure just gets sent as is.

**Comment by xenodium** [comment]
So it looks like `(plist-get (car (auth-source-search :host "api.openai.com")) :secret)` already returns a function, so I was hoping that didn't trigger prompt for your gpg passphrase. But... I think you can actually do the following and avoid a hook:

```
(setq chatgpt-shell-openai-key
      (lambda ()
        (funcall (plist-get (car (auth-source-search :host "api.openai.com"))
                            :secret))))
```

It should give you lazy loading, so you're prompt only when you first use the ChatGPT shell.

See if the above works for ya.

**Comment by MunsterPlop** [comment]
It works fine, thanks :).
If we're going with this method, I think the simpler `auth-source-pick-first-password` mentioned in #27 could also be an improvement:

```elisp
(setq chatgpt-shell-openai-key (lambda () (auth-source-pick-first-password :host "api.openai.com")))
```

**Comment by xenodium** [comment]
Thank you! Updated README.org.
