### ISSUE TITLE
[FR] Ask chatgpt about selected region, but prompting with history

### ISSUE THREAD

**Issue by Lenbok** [xenodium/chatgpt-shell#32]
You have some functions that act on a region with pre-canned prompts (e.g. `chatgpt-shell-describe-code`). This seems a common pattern where you want to make some request about the region. You can just use `chatgpt-shell-send-region` followed by manually typing the question, but it would be nice to facilitate this by reading the prompt from the user, *with history*. I've hacked together the following that you might want to incorporate after some tidying (maybe use a specific history var?):

```elisp
  (defvar my-chatgpt-shell-default-prompts '(
                                "Write a unit test for the following code:"
                                "Refactor the following code so that "
                                ))
  (defun my-chatgpt-ask-about-region ()
    "Ask ChatGPT about region using user supplied prompt."
    (interactive)
    (let ((prompt (read-from-minibuffer "Prompt: " nil nil nil nil my-chatgpt-shell-default-prompts)))
      (chatgpt-shell-send-to-buffer
       (concat prompt "\n\n"
               (buffer-substring (region-beginning) (region-end))))
      (chatgpt-shell--send-input)))

```
You can use M-p/M-f to scroll through previous and future history and edit if necessary.

**Comment by xenodium** [comment]
Good idea. Made `chatgpt-shell-chatgpt-prompt` region-aware. See if that works for ya.

**Comment by Lenbok** [comment]
Mostly, but I've opened #37 so we also get a future-history and ability to use vertico etc for selection.
