### ISSUE TITLE
Evil / Doomy compatible version

### ISSUE THREAD

**Issue by martinbaillie** [xenodium/chatgpt-shell#34]
(Please feel free to close if this is not the direction you are looking to take this package).

I am one of those heathens that use evil (Doom) and I'm very accustomed to using vterm in that context. 

I'm not familiar with eshell or comint, but do you think a similar evil UX is achievable (as an optional extra, evil-collection style)?

I guess what I mean is vi modal style manipulation of the `chatgpt-shell` buffer. Sorry I've not described this very well.

**Comment by xenodium** [comment]
Not too sure how to go about this (not on evil), but on initial look an implementation is prolly better to live in evil-collection?

**Comment by agzam** [comment]
@martinbaillie I'm using Doom, and it seems chatgpt-shell works with Doom (Evil) without any additional steps. What are you (or I) missing?

**Comment by martinbaillie** [comment]
Ah I raised this really early on and forgot. I too realised evil works fine!
