### ISSUE TITLE
Use display-buffer to show buffers

### ISSUE THREAD

**Issue by chrisbarrett** [xenodium/chatgpt-shell#35]
Hello,

The commands for displaying the chatgpt and dall-e buffers currently use `pop-to-buffer-same-window`. It would be nice if it used `display-buffer` instead, so the window display behaviour can be configured by the user.

To preserve the existing behaviour, you could add a custom variable which is set to `pop-to-buffer-same-window` and default to using that if non-nil. But if nil, use display-buffer. I think magit does something like this with `magit-display-buffer-function`.

Thanks very much for this package, it's so much more convenient than the web UI!

**Comment by xenodium** [comment]
try `(setq chatgpt-shell-display-function #'display-buffer)` in the latest.

> Thanks very much for this package, it's so much more convenient than the web UI!

Glad you like it!
