### ISSUE TITLE
chatgpt-shell-model-temperature bug

### ISSUE THREAD

**Issue by Dickby** [xenodium/chatgpt-shell#38]
fixing https://github.com/xenodium/chatgpt-shell/issues/36 didnt't really work, the variable is not customizable with customize-variable anymore. trying to set it with `set-variable` errors : Symbol’s function definition is void: nil

**Comment by xenodium** [comment]
Yikes. Sorry. I hadn't tried customize-variable. Ok try latest.

**Comment by Dickby** [comment]
Now it works,
Thanks a lot!
