### ISSUE TITLE
[FR] Streaming response

### ISSUE THREAD

**Issue by Lenbok** [xenodium/chatgpt-shell#39]
For longer responses you end up waiting with nothing to see for quite a while then a big dump (possibly more than a screen full) arrives. It would be much nicer UX to read the response as it comes back in.

It looks like there are a couple of forks that implement this already so hopefully it is not too hard.

**Comment by xenodium** [comment]
Ah yes. It's coming. May take me a little bit. Working and making things more generic so we can create shells from other LLM providers. Maybe even even those running locally.

**Comment by xenodium** [comment]
try `(setq chatgpt-shell-chatgpt-streaming t)`

**Comment by xenodium** [comment]
![stream](https://user-images.githubusercontent.com/8107219/229632703-4a1aff09-6e61-4cde-9c39-bd67cb697bd0.gif)
