### ISSUE TITLE
A more direct Assistant feature.

### ISSUE THREAD

**Issue by Dickby** [xenodium/chatgpt-shell#40]
There is an linux application called shell-gpt. Here the user can command chatGPT to take certain actions in the terminal. chatGPT will then provide a shell command that tries to do the prompted task, the user sees this shell command is is asked if it should be excecuted.
This could be adapted by chatgpt-shell. A command like chatgpt-shell-assistant, could prompt in the minibuffer, and prepend something like "Answer the following request with valid elisp code that implements the requested action: ". The result will be offered for excecution similar to the way shell-gpt does.

What do you think?

**Comment by xenodium** [comment]
Interesting idea. I suspect it'll get tricky to find a sweet spot for this sort of behaviour, so I'm adding an integration point and some building blocks (around ielm) for folks to implement own neat ideas.

You can achieve something like what you've described with:

```
(setq chatgpt-shell-response-post-process-function
      (lambda (response)
        (let* ((source-blocks (seq-filter (lambda (block)
                                            (or (string-equal (car block)
                                                              "emacs-lisp")
                                                (string-equal (car block)
                                                              "elisp")))
                                          (chatgpt-shell--markdown-source-blocks
                                           response)))
               (source-block (cdr (seq-first source-blocks))))
          (when (and source-block source-blocks)
            (if (eq (seq-length source-blocks) 1)
                (when (y-or-n-p "Execute emacs-lisp block?")
                  (chatgpt-shell-send-to-ielm-buffer (string-trim source-block) t))
              (message "Too many blocks to choose from"))))))
```

https://user-images.githubusercontent.com/8107219/229351118-cfb5596b-435d-4bea-a9b8-18177994f533.mov

**Comment by Dickby** [comment]
This is an example where the the "system" role can be handy. I think shell-gpt is not using "system" but prepends something to every user prompt. look how it's achieved that chatgpt will only output the code requested, and no extra information: https://github.com/TheR1D/shell_gpt/blob/main/sgpt/make_prompt.py
