### ISSUE TITLE
No such curl option `--fail-with-body`

### ISSUE THREAD

**Issue by Lenbok** [xenodium/chatgpt-shell#42]
Just installed chatgpt-shell on another machine and this new install fails with:

```
curl: option --fail-with-body: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
<gpt-ignored-response>
```

BTW, this machine (ubuntu 20.04 LTS) reports curl --verson as: `curl 7.68.0`

**Comment by xenodium** [comment]
Thanks for reporting. I'll fix the version check for this flag. Should be 7.76. 

https://daniel.haxx.se/blog/2021/02/11/curl-fail-with-body/
