### ISSUE TITLE
Shorten the conversation history.

### ISSUE THREAD

**Issue by Dickby** [xenodium/chatgpt-shell#43]
If conversations are long, eventually they become to long to be back presented to chatGPT because of the token limit. 
In those cases the history that is given back can be shortened. 
This is not perfect of course, but better than the conversation ending in an error, and the  only solution for continuing is to manually repeat parts of the conversation.

**Comment by xenodium** [comment]
Thanks for raising.

> and the only solution for continuing is to manually repeat parts of the conversation.

Have you considered setting `chatgpt-shell-transmitted-context-length`?

There's also https://github.com/xenodium/chatgpt-shell#saving-and-restoring-experimental

**Comment by Dickby** [comment]
To be honest, i didn't! Sorry for that.
At the same time, an automatic system that shortens the history, if a threashold is reached would be convenient.
How about a variable, that defines an "max expected size" for a request-completion pair, if the current conversation + this max size is longer than the token limit, it could crop the history so that there is enough space for the next request-completion pair. Another more manual, but also more dynamic solution, would be, to manually decide which conversation history pairs should be excluded. That way  the user could decide what part of the conversations history are important for the continuation.
But because the package has already ways to deal with long conversation histories, if you don't see the need of additional functionality for this, fee free to close this issue.

**Comment by xenodium** [comment]
Thanks for the suggestions. 

Counting tokens may get tricky to match how chatgpt does it. I can offer two options for now:

- Set context low enough to reduce chances of hitting issue. 
- Manually reduce context when you run into issues via M-x set-variable.

**Comment by Dickby** [comment]
I will go with the first suggestion, thanks.
Closing this issue
