### ISSUE TITLE
Add comments to region.

### ISSUE THREAD

**Issue by Dickby** [xenodium/chatgpt-shell#44]
`chatgpt-shell-explain-code` is already a nice thing. But how a function like `chatgpt-shell-add-comments-to-region` ? with a "system" message that explains that the code should be left totally unchanged, just some helpful, functionality explaining comments should be added to the presented code, we can expect a result that can be directly used to replace the region. I think this would be a really nice way to study some code, or find flaws in newly written code.

**Comment by Dickby** [comment]
Another thing that could be implemented in a similar way, is to present some region to chatgpt, and ask it to implement a function which is called from the code of that region, and copy it to the yank/kill-ring. This could work for simple functions if the function name, and the context of the region provides enough information about what the function should do.

**Comment by xenodium** [comment]
Thanks for the suggestions.

I have to be a little mindful of which functionality becomes part of the package, vs enabling users to build on top of it for preferred flows. Similar to #40, this can possibly be implemented by users.

Take a look at `chatgpt-shell-describe-code` as a guide.

```
(defun chatgpt-shell-describe-code ()
  "Describe code from region using ChatGPT."
  (interactive)
  (chatgpt-shell-send-to-buffer
   (concat "What does the following code do?\n\n"
           (buffer-substring (region-beginning) (region-end))))
  (chatgpt-shell--send-input))
```

**Comment by Dickby** [comment]
Hmm, it would be ease to change the your function to tell chatgpt to add comments instead of explaining the code. But the functionallity that i meant, is to not opening a chatgpt-shell buffer and having the result there, but to automaticly  replace the region with the commented code.

**Comment by xenodium** [comment]
Added more helpers that should enable ya to do what you're suggesting.

```emacs-lisp
(chatgpt-shell-post-chatgpt-prompt
 "hello"
 (lambda (response)
   (message "%s" response))
 (lambda (error)
   (message "%s" error)))
```
```emacs-lisp
(chatgpt-shell-post-chatgpt-messages
 `(((role . "user")
    (content . "hello")))
 (lambda (response)
   (message "%s" response))
 (lambda (error)
   (message "%s" error)))
```

**Comment by Dickby** [comment]
That works, thanks for the help!

for anybody who is interested in this, here is the code that implements what i wanted:

```
  (defun replace-active-region-with-string (replacement)
    "Replace the currently active region with REPLACEMENT."
    (when (use-region-p))
    (delete-region (region-beginning) (region-end))
    (insert replacement))

  (defun get-region-string ()
    "Returns the string that is enclosed by the buffer's active region."
    (when (region-active-p)
      (buffer-substring-no-properties (region-beginning) (region-end))))

  (defun my/gpt-add-comments ()
    (interactive )
    (replace-active-region-with-string
     (chatgpt-shell-post-chatgpt-prompt
      (format "please reproduce the following code and add declarative comments to it, leave the code itself as it is just add comments nothing else don't inset extra lines just add the comments behind the code in the same line :%s" (get-region-string)))))

```

**Comment by xenodium** [comment]
> That works, thanks for the help!

Great to hear!

> for anybody who is interested in this, here is the code that implements what i wanted:

Thanks for sharing!
