### ISSUE TITLE
Compilation warnings when using chatgpt-shell

### ISSUE THREAD

**Issue by ielnahhal** [xenodium/chatgpt-shell#46]
I added this chatgpt-shell to emacs on my OS. through quelpa package manager and I got those warnings which says that the code should be improved and developed 

those are the warnings I got in emacs warning buffer : 
Warning (comp): chatgpt-shell.el:94:1: Warning: defcustom for `chatgpt-shell-language-mapping' fails to specify type Disable showing Disable logging
Warning (comp): chatgpt-shell.el:189:13: Warning: Unused lexical argument `input' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:227:13: Warning: Unused lexical argument `input' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:343:31: Warning: Unused lexical argument `config' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:496:71: Warning: Unused lexical argument `url' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:496:71: Warning: Unused lexical argument `request-data' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:496:71: Warning: Unused lexical argument `response-extractor' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:496:71: Warning: Unused lexical argument `error-callback' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:574:44: Warning: reference to free variable `eshell-last-input-start' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:574:68: Warning: reference to free variable `eshell-last-input-end' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:584:44: Warning: reference to free variable `eshell-last-input-start' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:584:68: Warning: reference to free variable `eshell-last-input-end' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:597:1: Warning: Variable `curbuf' left uninitialized Disable showing Disable logging
Warning (comp): chatgpt-shell.el:597:60: Warning: Unused lexical variable `current-buffer' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:634:13: Warning: `mark-whole-buffer' is for interactive use only. Disable showing Disable logging
Warning (comp): chatgpt-shell.el:679:35: Warning: reference to free variable `chatgpt-shell--prompt-internal' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:706:42: Warning: reference to free variable `chatgpt-shell--prompt-internal' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:930:33: Warning: reference to free variable `chatgpt-shell--prompt-internal' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:952:30: Warning: Unused lexical variable `err' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:978:6: Warning: Unused lexical variable `err' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:994:8: Warning: docstring wider than 80 characters Disable showing Disable logging
Warning (comp): chatgpt-shell.el:1002:8: Warning: docstring wider than 80 characters Disable showing Disable logging
Warning (comp): chatgpt-shell.el:1102:13: Warning: assignment to free variable `view-exit-action' Disable showing Disable logging
Warning (comp): chatgpt-shell.el:629:8: Warning: the function `ielm-return' is not known to be defined. Disable showing Disable logging
Warning (comp): chatgpt-shell.el:576:74: Warning: the function `eshell-end-of-output' is not known to be defined. Disable showing Disable logging
Warning (comp): chatgpt-shell.el:576:45: Warning: the function `eshell-beginning-of-output' is not known to be defined. Disable showing Disable logging

**Comment by xenodium** [comment]
Hi @ielnahhal. Thanks for reporting! Are you by chance interested in helping out to fix these?
