### ISSUE TITLE
chatgpt-shell-restore-session-from-transcript not working as expected

### ISSUE THREAD

**Issue by rogsme** [xenodium/chatgpt-shell#50]
I'm using `main:8c2197ffff51f595ffe7ca1844b6b6604ba855b8` for this test.

Steps to reproduce:
- Create a testing session a save it with `chatgpt-shell-save-session-transcript`.
- Close the session and open a new one.
- Restore it with `chatgpt-shell-restore-session-from-transcript`.
- See the *Messages* buffer for the error. The shell loads only the fist line of the transcript.

The full error is here:
```elisp
funcall: Wrong number of arguments: (((v . #s(shell-maker-config "ChatGPT" (closure (t) (_command) (if chatgpt-shell-openai-key nil "Variable `chatgpt-shell-openai-key' needs to be set to your key.

Try M-x set-variable chatgpt-shell-openai-key

or

(setq chatgpt-shell-openai-key \"my-key\")")) (closure (t) (_command history callback error-callback) (shell-maker-async-shell-command (chatgpt-shell--make-curl-request-command-list (chatgpt-shell--make-payload history)) chatgpt-shell-streaming #'chatgpt-shell--extract-chatgpt-response callback error-callback)) (closure (t) (_command output) (chatgpt-shell--put-source-block-overlays) (if chatgpt-shell-on-command-finished-function (progn (funcall chatgpt-shell-on-command-finished-function output)))) (closure (t) (output) (if (chatgpt-shell-openai-key) (string-replace (chatgpt-shell-openai-key) "SK-REDACTED-OPENAI-KEY" output) output)))) (failed) (response) (command (role . "user") (content . "create a python function that sums two numbers")) (validate-command closure (t) (_command) (if chatgpt-shell-openai-key nil "Variable `chatgpt-shell-openai-key' needs to be set to your key.

Try M-x set-variable chatgpt-shell-openai-key

or
...
;; What follows is basically a "elispefied" version of my transcript.txt, so I removed it for brevity
```

What surprises me is the `Try M-x set-variable chatgpt-shell-openai-key`, since it is set and working without any problems (I can create the first session).

My setup looks like this:

```elisp
(require 'chatgpt-shell)
(setq chatgpt-shell-openai-key "my-super-secret-openai-key")
(setq chatgpt-shell-chatgpt-model-version "gpt-3.5-turbo")
(setq chatgpt-shell-chatgpt-streaming t)
(setq chatgpt-shell-chatgpt-system-prompt "You are a senior Python developer in charge of maintaining a very big application")
```

I'm attaching my `transcript.txt` file: [sumscript.txt](https://github.com/xenodium/chatgpt-shell/files/11183687/sumscript.txt)

If you need more info, just let me know!

**Comment by xenodium** [comment]
Thanks for the detailed @rogsme! I broke it, sorry. I was able to restore `sumscript.txt` with the latest fix. Try again with https://github.com/xenodium/chatgpt-shell/commit/3c5ddbc5e6f58aaa104a6498694ed9ab9b18e845

**Comment by rogsme** [comment]
Can confirm that https://github.com/xenodium/chatgpt-shell/commit/3c5ddbc5e6f58aaa104a6498694ed9ab9b18e845 works flawlessly. Closing this issue! Thanks!
