### ISSUE TITLE
Feature request: Proofread & replace in place

### ISSUE THREAD

**Issue by agzam** [xenodium/chatgpt-shell#53]
I just started using the `chatgpt-shell-proofreading-doc` feature, and I can't even describe how great it is, especially for someone like me, a non-native English speaker. At some point, I might even create custom variants for other languages that I frequently use. However, that's not what I wanted to ask about.

Is it possible to add a feature that can proofread and replace the selected region? Currently, it does it in the `*chatgpt*` buffer, but almost every time, I have to grab it from there and then go back to the previous buffer. I think this feature would be useful and quite popular. WDYT?

I would even dare to suggest that if no region is selected, proofread the entire content of the buffer. The header may have to change because we can't ask chatgpt to do it for a single paragraph.

**Comment by xenodium** [comment]
I need to think about how to do this more comprehensively (not just this command). Maybe all commands support a prefix option to insert inline the response.

In the mean time, this should get ya going for what you need: https://github.com/xenodium/chatgpt-shell/issues/44#issuecomment-1493409861

**Comment by agzam** [comment]
That is just what I needed. Thank you! You may close this issue whenever it's convenient.

**Comment by xenodium** [comment]
> That is just what I needed.

Perfect ;)

>  Thank you! 

Glad you're finding it useful.

**Comment by xenodium** [comment]
You might find the new generic `M-x chatgpt-shell-quick-modify-region` useful. Beware: It's still very fresh.

![proofread_x1 2](https://github.com/user-attachments/assets/34308725-c9e4-40fa-88c4-ce3ef35c2d5f)
