### ISSUE TITLE
Question: Usage from elisp?

### ISSUE THREAD

**Issue by NickSeagull** [xenodium/chatgpt-shell#54]
I was wondering if there is support for calling a function that does a "one-off" request and returns the output. This would be very useful for automating stuff.

On the other hand, maybe I'm just too much of a noob and that can be accomplished by somehow sending the arguments to the chatgpt-shell buffer and retrieving the output?

Thanks a lot for this project!

**Comment by xenodium** [comment]
Would `chatgpt-shell-post-prompt` or `chatgpt-shell-post-messages` do what you're after?

**Comment by NickSeagull** [comment]
Exactly! Thanks a lot ❤️
