### ISSUE TITLE
Cannot select gpt-4 for chatgpt-shell-model-version

### ISSUE THREAD

**Issue by ReggieMarr** [xenodium/chatgpt-shell#55]
When I set the model version to gpt-4 like so:
```
chatgpt-shell-model-version is a variable defined in chatgpt-shell.el.

Value
"gpt-4"

Original Value
"gpt-3.5-turbo"
```

I get the following response:

Can you provide some config I can use for my doom emacs 
<shell-maker-end-of-prompt>
The model: `gpt-4` does not exist

Am I doing something wrong or is this just not yet supported?

**Comment by xenodium** [comment]
I think it's "gpt-4" but can't confirm now. Could you look at API docs? I'm on mobile.

Having said this, I can't verify it works myself since I don't yet have API access to 4 (only web chat). I'm on the waiting list. Do you have 4 API access? If you're willing to momentarily share a key with me (privately) I can make sure it all works.

**Comment by xenodium** [comment]
Folks seem to be using "got-4":

https://github.com/benjamin-asdf/chatgpt-shell/blob/7ee811d0aacb1adb2bd6aeee0c6e41fc053e12aa/chatgpt-shell.el#L69
https://github.com/martinbaillie/dotfiles/blob/bfe92cad71e03b8a75ccdfa206f470d22b308c6d/config/emacs/config.org?plain=1#L1930

**Comment by ReggieMarr** [comment]
That's odd. It was "working" with gptel but now I'm questioning that. I wonder if it has anything to do with me being in canada...
I have been able to access GPT-4 from openai's ui though

**Comment by xenodium** [comment]
>  I have been able to access GPT-4 from openai's ui though

I can too from web UI, but still on waiting list for API access. Access to web UI vs API is granted/requested separately: https://openai.com/waitlist/gpt-4-api

**Comment by strickinato** [comment]
I have access to the `gpt-4` model through my API key and can confirm it works fine with `chatgpt-shell`.

**Comment by xenodium** [comment]
Thanks for confirming @strickinato

**Comment by aiwebdude** [comment]
I made the changes in the .el and in customize and no longer get the model gpt-4 does not exist. however it reports based on GPT-3 ... is that correct? is there an instruction somewhere like: this is what you do to change the model and here is how you can see that it worked ? (Do I need 2 keys? one for 3.5 plan and one for 4 plus api plan?)

**Comment by xenodium** [comment]
1. `M-x chatgpt-shell-swap-model-version` to 4. 
2. Make a request.
3. If requests succeeds, your gpt4 setup and API are working fine.

**Comment by aiwebdude** [comment]
thank you, I read that but on GNU Emacs 29.1 (build 2, x86_64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6.8 (Build 21G725)) of 2023-07-30
 I don't have chatgpt-shell-swap-model-version and I have no occurence of "swap" in chatgpt.el do I have to install something?
