### ISSUE TITLE
Symbol’s value as variable is void: comint--prompt-rear-nonsticky

### ISSUE THREAD

**Issue by sanel** [xenodium/chatgpt-shell#58]
Running latest chatgpt-shell.el in Emacs 27.2 would yield this error:
```
Symbol’s value as variable is void: comint--prompt-rear-nonsticky
```
I assume this is added in newer Emacs versions and IMHO should be checked for it's presence. I solved it by evaluating below code in `*scratch*`, which is a copied version from the latest comint.el, but still, it should be ignore if is not defned.

```elisp
(defconst comint--prompt-rear-nonsticky
  '( field inhibit-line-move-field-capture read-only font-lock-face
     insert-in-front-hooks))
```

**Comment by xenodium** [comment]
Sorry for the break. Thanks for reporting. Should be fixed now.

**Comment by sanel** [comment]
Thank you!
