### ISSUE TITLE
Typing assistant

### ISSUE THREAD

**Issue by agzam** [xenodium/chatgpt-shell#59]
I am thoroughly impressed with this package that I can't seem to put down. It got me thinking - have you ever considered creating a context-aware typing assistant? Not like dabbrev or other tools that rely on company or corfu, though there are situations where those options would come in handy.

What if you could design something to rival even Gmail's "smart compose," or better yet, imagine an autocomplete feature that's 100 times better than any other currently available on Emacs. Picture this: you start typing, and an overlay appears with a suggestion to complete your sentence, intuitively based on the context of your writing. Wouldn't that be amazing? Is something like that even possible, given the non-concurrent nature of Emacs model?

**Comment by xenodium** [comment]
> I am thoroughly impressed with this package that I can't seem to put down.

Nice to hear. Emacs can enable lots of handy and fun things with it (like https://indieweb.social/@xenodium/110227186721704189).

> an overlay appears with a suggestion to complete your sentence, intuitively based on the context of your writing.  Wouldn't that be amazing? 

Depends on personal eagerness to send own writing to it, but putting that aside, yes ;)

> Is something like that even possible, given the non-concurrent nature of Emacs model?

Should be possible. Company mode does async handling https://www.badykov.com/emacs/async-company-mode-backend and suggestions also https://github.com/dieggsy/esh-autosuggest. I'm sure capf can do all this too, but I haven't done a whole lot with it.

I'm thinking it's usefulness would depend on the quality of the suggestions and roundtrip overhead of the implementation. For the quality, I suppose you can experiment as is with `chatgpt-shell-prompt` (region selected). Would be great to know what kind of prompt you used if you get good results. For the overhead, maybe it can use the streaming API if needed.

There are lots of interesting possibilities here... I'm thinking that this package can perhaps provide some building blocks and folks can build other packages on top of it. For example, either `chatgpt-shell-post-messages` or `chatgpt-shell-post-prompt` can already send requests either sync or async, which could get folks started.

**Comment by agzam** [comment]
> I'm thinking that this package can perhaps provide some building blocks and folks can build other packages on top of it.

Yup. Here's one example. I took your `(chatgpt-shell-post-prompt)` and added diff display. It manipulates text in active region (or whole buffer) and then shows the diff of the changes. I just can't stop using this stuff.

```
(defun +replace-region-with-string (replacement)
  "Replace region or buffer content with REPLACEMENT."
  (if (use-region-p)
      (delete-region (region-beginning) (region-end))
    (delete-region (point-min) (point-max)))
  (insert replacement))

(defvar chatgpt-improve-text-hist
  '("Improve this text, don't be too formal:"
    "Improve this code:"
    "Add comments to the following code snippet:"
    "Improve and make it witty:"))

;;;###autoload
(defun +chatgpt-shell-improve-text (prompt-str)
  "Send given text to chat-gpt for given PROMPT-STR."
  (interactive "P")
  (message "beep-bop... checking your crap...")
  (let* ((text (if (region-active-p)
                   (buffer-substring-no-properties
                    (region-beginning)
                    (region-end))
                 (buffer-substring-no-properties
                  (point-min)
                  (point-max))))
         (default-prompt "Improve the following text:")
         (prompt (if prompt-str
                     (read-string "Prompt to use: "
                                  default-prompt
                                  'chatgpt-improve-text-hist)
                   default-prompt))
         (new-text (chatgpt-shell-post-prompt
                    (format "%s\n%s" prompt text)))
         (fst-buf (with-current-buffer (generate-new-buffer " * chat-gpt text 1 *")
                    (insert text)
                    (current-buffer)))
         (snd-buf (with-current-buffer (generate-new-buffer " * chat-gpt text 2 *")
                    (insert new-text)
                    (current-buffer)))
         (diff-win (diff fst-buf snd-buf "--text" 'no-async)))
    (+replace-region-with-string new-text)
    (message "I hope you like it")

    ;; cleaner diff
    (with-current-buffer (window-buffer diff-win)
      (read-only-mode -1)
      (goto-char (point-min))
      (dolist (r '("^diff.*\n"
                   "^. No newline at end of file\n"
                   "^. No newline at end of file\n"
                   "^Diff finished.*$"))
        (re-search-forward r nil :noerror)
        (replace-match ""))
      (visual-line-mode))
    (kill-buffer fst-buf)
    (kill-buffer snd-buf)))
```

Here's the sentence above after I send it over with a prompt: "Improve the following text. Use slang"

> Yo. Check it. I took your `(chatgpt-shell-post-prompt)` and put in some diff display. It's lit. It messes with the text in the active region (or the whole buffer) and then shows the diff of the changes. I'm seriously hooked on this stuff.

**Comment by xenodium** [comment]
>  I just can't stop using this stuff.

;) it is fun plugging it to Emacs

>  It manipulates text in active region (or whole buffer) and then shows the diff of the changes.

Just tried it. Neat! The diff is handy.

**Comment by xenodium** [comment]
I think chatgpt-shell can now power creative usages with existing functions that users can build on top of? Ok to close this issue?
