### ISSUE TITLE
Paste response directly at the point where chatgpt-shell-prompt is called

### ISSUE THREAD

**Issue by hokreb** [xenodium/chatgpt-shell#64]
Its really a very nice emacs packages! I liked it very much!

Here two ideas to improve the usability for day to day usage.:

It would be very handy, if the answer to a question would be inserted directly at the point where the cursor in the emacs buffer is. By this one could easily created documents (eg in org files) without needing to copy them from the chatgpt shell window.

It would be also very handy, when the answer to a question of a marked region, would be directly  placed in the next new line down it.

**Comment by xenodium** [comment]
> Its really a very nice emacs packages! I liked it very much!

Glad to hear it. Thank you!

> Here two ideas to improve the usability for day to day usage.

Have had similar requests in #44 and #53. Maybe it's time to give it a go ;)

So, I've implemented an initial version of it. At the moment it's only available in `chatgpt-shell-prompt` command if you invoke it with a prefix (ie. C-u). It's async and keeps history in shell (this helps keep context for further requests).

Here's what it looks like in action

![2023-04-26-23:37:06-Emacs_x1 5](https://user-images.githubusercontent.com/8107219/234718949-8391f7d5-aa28-4139-a265-190a2f81e449.gif)

I'd like to roll it out to other commands and also control default behaviour (ie. what C-u prefix does): inline vs shell focus.

**Comment by xenodium** [comment]
As of 10fd3ee, most non-shell queries are now defaulting to inserting in file. Can be inverted with prefix `C-u` or changing the default in `chatgpt-shell-insert-queries-inline`. This should cover the feature request. Closing.
