### ISSUE TITLE
Timeout.

### ISSUE THREAD

**Issue by agzam** [xenodium/chatgpt-shell#66]
Longer queries timeout. Which might be not the big problem by itself, yet it would be nice ~if there's a way to extend the duration~ (there is). Also, I think they should fail more gracefully. Currently, it looks like as if it's appending error message without any prior delimeter, simply adds to the output, something like: "curl: (28) Operation timecurl: (28) Operation timed out after 60003 milliseconds with 47011 bytes received"

**Comment by xenodium** [comment]
Have you tried this variable? https://github.com/xenodium/chatgpt-shell/blob/6dc5dafd46554ad0d4677b9e57790d31570f2b0c/chatgpt-shell.el#L47

**Comment by xenodium** [comment]
Looks like you're good with the existing variable. Closing.
