### ISSUE TITLE
Exceeded current quota API

### ISSUE THREAD

**Issue by largocreatura** [xenodium/chatgpt-shell#69]
When I make a query from the chatgpt-shell prompt, it returns the following message: "You exceeded your current quota, please check your plan and billing details. Curl: (22) The requested URL returned error: 429". However, in the usage section of the OpenAI dashboard, it shows that I have not yet made any use of the API. Curl v8.0.1. Emacs v28.1

**Comment by xenodium** [comment]
This error is coming straight from OpenAI API. Not sure there's much we can do on client side. Maybe set `chatgpt-shell-transmitted-context-length` to a small value?

**Comment by xenodium** [comment]
You're welcome! Will close this one.
