### ISSUE TITLE
[SUGGEST] Make `chatgpt-shell--url` as `defcustom` option

### ISSUE THREAD

**Issue by stardiviner** [xenodium/chatgpt-shell#73]
OpenAI API URL supports partial key authorization.

I suggest `chatgpt-shell--url` be a custom option so that user can customize it. (I know `defvar` can be customized too)

**Comment by xenodium** [comment]
Good idea. Thanks for filing. Would you be keen to send PR also renaming `chatgpt-shell-url` and add some sample url options in the docstring?

**Comment by stardiviner** [comment]
Make PR here, my description may not good enough, modify as your need.

**Comment by xenodium** [comment]
Thank you! Merged PR. Closing issue.
