### ISSUE TITLE
Repeating

### ISSUE THREAD

**Issue by agzam** [xenodium/chatgpt-shell#76]
Chat-GPT by nature is not deterministic - sending the same query multiple times may return different results each time.

I'm finding myself over and over again wanting to repeat the same prompt or ask it to try again (with the previous one). It's not a problem when that's happening in the shell buffer. But when you're using something like `(chatgpt-shell-post-prompt)` - it's not easily possible.

Can we please discuss some mechanisms of how this could be done? Maybe also explore https://www.gnu.org/software/emacs/manual/html_node/emacs/Repeating.html?

**Comment by xenodium** [comment]
Did you look at `chatgpt-shell-model-temperature`?

**Comment by xenodium** [comment]
Maybe also look at `chatgpt-shell-prompt` implementation. History can likely help with repeating things with the last used prompt.
