### ISSUE TITLE
Stop words

### ISSUE THREAD

**Issue by agzam** [xenodium/chatgpt-shell#77]
*This isn't an actual issue or a request. It's a question*

I just realized, when asking chatgpt a question, one can safely remove stop words and in most cases, it shouldn't affect the quality of the answer. Have you ever thought about reducing the noise, saving some polar bears, and reducing the number of tokens?

Has anyone tried removing these and checked if it affects the results at all?

*a, an, and, are, as, at, be, but, by, for, if, in, into, is, it, no, not, of, on, or, such, that, the, their, then, there, these, they, this, to, was, will, with*

Removing stop words from a prompt generally will not have a significant impact on the quality of the response. However, it is important to note that some stop words may be more important than others, depending on the context of the prompt.

For example, if you ask "What is the capital of France?", the word "the" is a stop word that can be safely removed without affecting the meaning of the question. However, if you ask "What is the code for accessing the bank account?", the word "the" in this case is important and removing it may change the meaning of the question.

So, the question is: when asking ChatGPT for example to analyze the content of a buffer/html-page/pdf/text paragraph/etc., are there any benefits of automatically removing (without context analysis) all those stop-words?

**Comment by xenodium** [comment]
> So, the question is: when asking ChatGPT for example to analyze the content of a buffer/html-page/pdf/text paragraph/etc., are there any benefits of automatically removing (without context analysis) all those stop-words?

From general observation I would say no, but I haven't paid too much attention. I was already ommitting these words for search engines. I'm no LLM prompt expert though. Maybe more of a question for https://reddit.com/r/chatgpt?

**Comment by xenodium** [comment]
I think we can close this one? Please re-open if there's anything else pending.
