### ISSUE TITLE
Don't switch to chatgpt buffer if it is already displayed in another window

### ISSUE THREAD

**Issue by tmalsburg** [xenodium/chatgpt-shell#78]
Don't switch to chatgpt buffer if it is already displayed in another window, e.g. when using `chatgpt-shell-proofreading-doc` but also elsewhere.  Motivation: 1. no need to show the chatgpt buffer in two windows, 2. it's useful to see chatgpt output and the buffer in which I'm working side-by-side.

**Comment by xenodium** [comment]
The proofreading function and other similar ones have been revamped. From the function name, it looks like you're on an older version. Can you rey the latest please?

**Comment by tmalsburg** [comment]
Found it (`INVERT-INSERT-INLINE` option on `chatgpt-shell-send-to-buffer`).  Cool package.  Thank you.

**Comment by xenodium** [comment]
Also check `chatgpt-shell-insert-queries-inline`
