### ISSUE TITLE
wrong-number-of-arguments on region functions

### ISSUE THREAD

**Issue by guibor** [xenodium/chatgpt-shell#79]
When I use functions that act on a region, e.g `chatgpt-shell-proofread-region` or `chatgpt-shell-explain-code`

I get the following error:

`(wrong-number-of-arguments #<subr shell-maker--send-input> 2)`

**Comment by xenodium** [comment]
Looks like a mismatch of versions. Can you ensure both chatgpt-shell and shell-maker are updated to the latest?

**Comment by guibor** [comment]
That fixed the issue. Thanks! Might be worth then just providing an indicative error.

**Comment by xenodium** [comment]
Will keep it in mind. Ideally something more high level that prompts user to update as finer grained checks would get hard to maintain. On the whole, update the two packages to the latest of you run into an issue in case I’ve already fixed it.
