### ISSUE TITLE
Installing in doom-Emacs

### ISSUE THREAD

**Issue by OrionRandD** [xenodium/chatgpt-shell#8]
This is how I made this work in doom-Emacs:

;; (add-load-path! "~/.emacs.d/local-repo/chagpt-shell")
(load-file "~/.emacs.d/local-repo/chatgpt-shell/chatgpt-shell.el")
(require 'chatgpt-shell)
(setq chatgpt-shell-openai-key "my key")

I had to load the file directly, because it didn't load through calling the directory itself

As a susggestion, could you implemente a "you.com" AI and a BARD AI chatgpt-shell like as well?

https://you.com/search?q=who+are+you&tbm=youchat&cfr=chat
https://bard.google.com/

And as a pull request, I would suggest the function to work in vterm as well...
The installation is not an issue, by the way...
Thx for the function...

**Comment by xenodium** [comment]
Hiya @OrionRandD, I'm unfortunately not familiar with Doom-specifics, but looks like @claytonrcarter's suggestion (thank you!) takes care of it for ya? If so, feel free to close this issue.

**Comment by OrionRandD** [comment]
> I think you can make that doomier:
> 
> ```emacs-lisp
> ;; ~/.doom.d/packages.el
> (package! chatgpt-shell
>   :recipe (:host github :repo "xenodium/chatgpt-shell"))
> 
> ;; ~/.doom.d/config.el
> (after! chatgpt-shell
>   (setq chatgpt-shell-openai-key "MY KEY"))
> 
> ;; then `doom sync`, restart Emacs, and `M-x chatgpt-shell`
> ```
> 
> At least, that worked for me...

Thx a lot...

**Comment by xenodium** [comment]
> I will close, although vterm is not doom specifics.

The package is comint-oriented, so unfortunately vterm is out of scope.
