### ISSUE TITLE
[Feature request] Customisations for non-shell commands

### ISSUE THREAD

**Issue by guibor** [xenodium/chatgpt-shell#80]
The default, which is to write the information directly in the file which is typically a code file makes less sense.
(This is a feature request, not an issue). 
Ideally user could customize between
- adding at point (current behaviour)
- switch to shell
- new buffer
- transient buffer
(the last makes most sense to me)

**Comment by xenodium** [comment]
Have you looked at `chatgpt-shell-insert-queries-inline`

**Comment by guibor** [comment]
Thanks! This helps a lot. I think that the other options are interesting, and perhaps differentiating between general prompts and describing/explaining prompts.

Love this package!

**Comment by xenodium** [comment]
Glad this helps. In the future, I may look into adding finer grained options you described. Are you interested in contributing them?

> Love this package 

Nice to hear

**Comment by mpereira** [comment]
I echo the sentiment regarding this package, and would add that having the contents of `chatgpt-shell-explain-code` show up in a [posframe](https://github.com/tumashu/posframe) would be really convenient.

**Comment by xenodium** [comment]
@guibor check `chatgpt-shell-prompt-query-response-style`. This now offers `inline` `shell` and `other-buffer`.

`other-buffer` provides the transient experience you mentioned and behaviour can be further customized via `display-buffer-alist`.

Will close feature request. We can start using these and see how we get on with current options. Can revisit later on after some usage.
