### ISSUE TITLE
[Feature request] async babel execution

### ISSUE THREAD

**Issue by falematte** [xenodium/chatgpt-shell#81]

**Comment by xenodium** [comment]
Thanks for filing the request. Babel by default is synchronous. Do you have suggestions? I only know of a third party package for it, which I haveb't tried: https://github.com/astahlman/ob-async

Are you keen to contribute this feature?

**Comment by falematte** [comment]
Thank you for this excellent package that I am beginning to explore. Although I am not able to do it myself, I know that several other packages are capable of it, particularly for Python scripting. This feature is very useful because it allows everything to run in the background, so you can continue working in Emacs rather than being stalled while a task finishes.

**Comment by xenodium** [comment]
More details would help here so I can take a look at specific packages. Are you referring to ob-python? Different package? Got a link?

**Comment by falematte** [comment]
I'm not quite sure which package you're referring to, but this is implemented by default in python babel blocks. So I believe is in ob-python.

**Comment by xenodium** [comment]
> I'm not quite sure which package you're referring

I'm not aware of specific packages other than [ob-async](https://github.com/astahlman/ob-async), but looks like you know of several ones? `I know that several other packages are capable of it, particularly for Python scripting.`

Any pointers on how other packages achieve async ob handling would help be achieve in this chatgpt-shell. If you can point me to concrete packages that do it (links are best), I can take a look, but `several other packages are capable of it` is a little vague unfortunately.

> but this is implemented by default in python babel blocks. So I believe is in ob-python.

ob-python is synchronous for me. I tested with:

```
#+begin_src python :python python3
  import time
  print("hello 1")
  time.sleep(3)
  print("hello 2")
#+end_src
```

Are you using different snippet header params?

**Comment by falematte** [comment]
Probably I was wrong. Sorry and thank you for your answer. Maybe this package can help? https://github.com/astahlman/ob-async

**Comment by wmedrano** [comment]
I got `ob-async` to work by just .... commenting out `(require 'org)` ob-.*shell.

I'm not good enough at ELisp to know what should be done. It resolves the cyclic dependency created by what I assume is an `ob-async` subprocess but I'm not sure that removing `(require 'org)` is a ELisp "best practice".

**Comment by xenodium** [comment]
@wmedrano thanks for investigating this! Looks like we can relax the require and use `org-element` in `ob-chatgpt-shell` and remove altogether from `ob-dall-e-shell`. Pushed the change. Closing this issue, but please reopen if still needed.
