### ISSUE TITLE
Display dall-e images in org-mode by default

### ISSUE THREAD

**Issue by ParetoOptimalDev** [xenodium/chatgpt-shell#82]
Right now I have to:

- execute source block
- M-x `org-toggle-inline-images`
- M-x `org-toggle-inline-images`

**Comment by xenodium** [comment]
Try this https://github.com/xenodium/ob-swiftui#auto-refresh-results-file-image

if that works for you, mind sending a PR updating the docs here?

**Comment by xenodium** [comment]
Can also make it part of the setup function

**Comment by xenodium** [comment]
This is now part of `(ob-dall-e-shell-setup)`. Evaluate that in the latest and it should automatically take care of showing them up.

**Comment by xenodium** [comment]
Thanks. No worries. It was a quick one.
