### ISSUE TITLE
Add ability to have multiple shells

### ISSUE THREAD

**Issue by gopar** [xenodium/chatgpt-shell#84]
Hey, awesome package :)

Is there a way to allow creating of multiple buffers with different engines?

I have questions I would like to ask gpt 3.5 but there will be a subset of questions I will want to ask gpt4 only (mainly code) 

I don't want to default to gpt4 all the time, since 3.5 just does as good a job and is faster.

**Comment by xenodium** [comment]
> Hey, awesome package :)

Thank you

> Is there a way to allow creating of multiple buffers with different engines?

Not at the moment. Multi-instance support would need work. Having said that, something that could be easily added is the ability to swap engine versions with completion.

How about something like:

```emacs-lisp
(defcustom chatgpt-shell-model-versions
  '("gpt-3.5-turbo" "gpt-4") "")

(defun chatgpt-shell-swap-model-versions ()
  (setq chatgpt-shell-model-version
        (completing-read "Model version: "
                         chatgpt-shell-model-versions nil t)))
```

**Comment by gopar** [comment]
Saw you added this in the package. Thanks!

Looks like there's no way to update the prompt or buffer name (defcustom) to update with the current model in use?

**Comment by xenodium** [comment]
There isn't at the moment, but heads-up that either of these can break other functionality without additional work. The context/history is extracted using the shell prompt and is relying on uniform value. Buffer name may be easier (updating the shell configuration).

**Comment by xenodium** [comment]
> Looks like there's no way to update the prompt or buffer name (defcustom) to update with the current model in use?

As of 296475c, you should be able to see it in the prompt and updated with `chatgpt-shell-swap-model-version`. Please report issues.

![swap](https://user-images.githubusercontent.com/8107219/237009515-e8dbdd3e-6c8e-4a66-8113-1871f071be5d.gif)

**Comment by xenodium** [comment]
There is an initial multi-session implementation in a separate branch. See #122 for details.
