### ISSUE TITLE
[Feature request] Extend markdown rendering

### ISSUE THREAD

**Issue by guibor** [xenodium/chatgpt-shell#85]
ChatGPT uses markdown for regular responses (e.g ** bold ** and more).
The suggestion is to add to the prompt default to add a markdown tag when the response is in markdown, so that it's nicely rendered in the ChatGPT shell window.

**Comment by xenodium** [comment]
> add a markdown tag when the response is in markdown

Could you share more details? Maybe an example of the default prompt and what effect it should have on the output? At present blocks and inline code are handled as markdown.

**Comment by guibor** [comment]
See example below.

I actually think that changing the prompt is probably not the best solution and it may be better to have a setting to display markdown markers elegantly (since ChatGPT uses them).

![Screenshot 2023-05-07 at 8 27 07](https://user-images.githubusercontent.com/4966289/236659491-066938de-b686-43c6-a0db-8a21747d0640.png)

**Comment by xenodium** [comment]
Got it. Renamed feature request title. This could maybe be done by extending the overlay handling (add more regular expressions), but needs experimenting s little. Not sure when I'll get to it. Are you keen to contribute?

**Comment by xenodium** [comment]
Extended basic markdown support. May have some bugs, please file if you find some.

<img width="687" alt="Screenshot 2023-05-14 at 01 03 42" src="https://github.com/xenodium/chatgpt-shell/assets/8107219/18273107-16bb-497d-9c1b-564b32bca489">

**Comment by guibor** [comment]
This is awesome! I noticed it's a bit inconsistent though, for example the markdown display tends to disappear from previous answers and I didn't get the same formatting for the palette question.

![image](https://github.com/xenodium/chatgpt-shell/assets/4966289/68cdc7c9-77cc-4256-a3dd-da1ffb6cbca1)

But this is really great!

**Comment by xenodium** [comment]
ps. thanks for the support @guibor!
