### ISSUE TITLE
Entering 'Please reduce the length of the messages.'  loop  ?

### ISSUE THREAD

**Issue by fenix011** [xenodium/chatgpt-shell#86]
After a while, chatGPT says :  

 ``` This model's maximum context length is 4097 tokens. However, your messages resulted in 5017 tokens. Please reduce the length of the messages.  ```

 and  stops answering my questions but seems to enter an infinite loop repeating the same message again and again instead of ... haha xD      

What am i missing ?  

Thanks, thanks, thanks

**Comment by xenodium** [comment]
To have contextual conversations, the history must be sent for every API request. When it reaches past limits, you start getting these errors. It's not straightforward AFAIK to accurately calculate the limit. 

Options:

- Clear the history: just type `clear`.
- Reduce `chatgpt-shell-transmitted-context-length`.

**Comment by fenix011** [comment]
Nice to know ._ Page 2.2.md Assuming that context is an important factor for chatgpt to provide a more reasoned and accurate answer... ummh. How to avoid clearing the relevant past context ? . I feel like kind of  wishlisting now... :-) Is there a way to mantain part of the context (say, by means of deleting the unuseful parts of or something like ? ) ? . Err... is there a way to mantain different threads of conversations in different shell buffers so that the contexts can be more easily maintained sort of ?

**Comment by xenodium** [comment]
> Is there a way to mantain part of the context (say, by means of deleting the unuseful parts of or something like ? ) ? .

You could `chatgpt-shell-save-session-transcript` edit the text file and then `chatgpt-shell-restore-session-from-transcript` but not super practical. 

> Err... is there a way to mantain different threads of conversations in different shell buffers so that the contexts can be more easily maintained sort of ?

This isn't possible at the moment. Needs work but also not sure how to predictably handle all commands that send queries to the shell from other commands. 

I'm thinking setting `chatgpt-shell-transmitted-context-length` to a smaller number may just be good enough even if mixing topics as follow-ups typically refer to something in the last few queries.

**Comment by xenodium** [comment]
@fenix011 I've added a very rough/experimental way (needs more thorough validation)

Try it with:

```emacs-lisp
(setq chatgpt-shell-transmitted-context-length
      #'chatgpt-shell--approximate-context-length)
```

Feel free to improve `chatgpt-shell--approximate-context-length`

**Comment by xenodium** [comment]
@fenix011 have you had a play with this? Worth enabling by default?

**Comment by xenodium** [comment]
`chatgpt-shell--approximate-context-length` is now default for a couple of weeks. Not heard issues so far. Gonna close this issue. Lemme know if you run into issues.
