### ISSUE TITLE
[Feature request] Maintain ChatGPT sessions in org babel

### ISSUE THREAD

**Issue by stardiviner** [xenodium/chatgpt-shell#87]
https://github.com/xenodium/chatgpt-shell/blob/020a0f046c333a3ba033a0509f3750c76de10b9d/ob-chatgpt-shell.el#L54

BTW, can you explain the usage of header arguments `:preface`, `:version` in README?

Thanks for your package. Very useful.

**Comment by xenodium** [comment]
`:preface` was broken. I've fixed the issue, but renamed `:system`. Both `:system` and `:version` are now documented in README.

> Maintain ChatGPT sessions in org babel

I've added a `:session` header, which should hopefully serve the session use-case but make it more deterministic by takeing context from current buffer. For example:

```org-mode
#+begin_src chatgpt-shell
  tell me a random day of the week
#+end_src

#+RESULTS:
Wednesday

#+begin_src chatgpt-shell :system "always respond like a pirate"
  hello
#+end_src

#+RESULTS:
Ahoy there, me hearty! How be ye today?

#+begin_src chatgpt-shell :context t
  what was the day you told me and what greeting?
#+end_src

#+RESULTS:
The day I told you was Wednesday, and the greeting I used was "Ahoy there, me hearty! How be ye today?"
```

Closing feature request. Please file any bugs if you run into issues.

**Comment by stardiviner** [comment]
Thanks for adding feature, @xenodium 👍🏻
