### ISSUE TITLE
[Feature request] Use other GPT providers (preferably free ones)

### ISSUE THREAD

**Issue by Dickby** [xenodium/chatgpt-shell#88]
My openAI api expired, I deleted my account there, and i'm not planing to create a new one.
Other people might not want to create an account at all, and i guess lot's of people from the emacs community are falling in that category. There are some ways to get the service of openAI without an api key:
https://github.com/aandrew-me/tgpt
https://github.com/xtekky/gpt4free.

Please consider using similar ways to provide a chatgpt-shell without the need to create an openAI account.
Thanks

**Comment by xenodium** [comment]
Unless there's a legitimate and equivalent API available, with similar ChatGPT semantics/structure, it would be out of scope for this project.
