### ISSUE TITLE
blank result

### ISSUE THREAD

**Issue by arademaker** [xenodium/chatgpt-shell#89]
Emacs 28.2 from http://emacsformacosx.com running on MacOS 13.3.1. I have in my .init.el

```elisp
(use-package chatgpt-shell
  :ensure t
  :custom
  ((chatgpt-shell-openai-key
    (lambda ()
      (auth-source-pass-get 'secret "..."))))) <- my key here
```

I started with `chatgpt-shell`

But I got no output 

```
ChatGPT(3.5-turbo)> Alex
<shell-maker-end-of-prompt>


<shell-maker-failed-command>ChatGPT(3.5-turbo)> 
```

**Comment by arademaker** [comment]
Emacs don't show the marks `<shell-maker-end-of-prompt>` and `<shell-maker-failed-command>`

**Comment by xenodium** [comment]
Try `(setq shell-maker-logging t)` and share the logs.

**Comment by arademaker** [comment]
Now it seems to be waiting response, but nothing happens

```
// Request

curl https://api.openai.com/v1/chat/completions --fail-with-body --no-progress-meter -m 180 -H Content-Type: application/json -H Authorization: Bearer nil -d {"stream":true,"model":"gpt-3.5-turbo","messages":[{"role":"system","content":"Always show code snippets in markdown blocks with language labels."},{"role":"user","content":"Alex"}]}


```

**Comment by xenodium** [comment]
Try to run that command from a terminal and see if that succeeds

**Comment by xenodium** [comment]
`-H Authorization: Bearer nil`

The key is missing.

It should looks like: `-H Authorization: Bearer SK-REDACTED-OPENAI-KEY`

**Comment by xenodium** [comment]
Ensure `(auth-source-pass-get 'secret "...")` returns the key.

**Comment by arademaker** [comment]
OK, my mistake... sorry. Now working:

```elisp
(use-package chatgpt-shell
  :ensure t
  :custom
  ((chatgpt-shell-openai-key "MY-KEY-HERE"))
```

So silly,  I didn't pay attention properly.  Now working.
