### ISSUE TITLE
`chatgpt-shell-add-??-command-to-eshell` not making "??" look at previous input

### ISSUE THREAD

**Issue by mpereira** [xenodium/chatgpt-shell#90]
Hi @xenodium,

First of all, thank you for your continued work on these great packages.

I might be doing something wrong here. I added `chatgpt-shell-add-??-command-to-eshell` to my `eshell-mode-hook` and when I input "??" in an eshell buffer it doesn't get the command before inputting "??", but "??" itself.

![output-2023-05-15-15:43:47](https://github.com/xenodium/chatgpt-shell/assets/112426/df3aae37-3230-4338-99f1-b577363918ac)

| Package      | Version                                                      |
|--------------|--------------------------------------------------------------|
| chatgpt-shell| 0.32.1                                                       |
| shell-maker  | 0.21.1, 20230513.1256 (195cda9b06c2c9996c586cabdba9c79f23ab12e7)|

**Comment by mpereira** [comment]
The issue here was on my side. I had a conflicting alias for "??" which was causing the issue.

**Comment by xenodium** [comment]
Ah, thanks for reporting back. I was narrowing down my config to see if it was down to different eshell configuration.

Beware, this integration is a little ~~experimental~~ flaky. I sometimes get incomplete ChatGPT responses. If you have improvement PRs, very much welcome.
