### ISSUE TITLE
Make ChatGPT function to return result

### ISSUE THREAD

**Issue by gnusupport** [xenodium/chatgpt-shell#92]
I understand there is shell, but please make the function that will return the result, something like:
`
(chatpgt STRING)`

That would return the ChatGPT response.

**Comment by xenodium** [comment]
Please take a look at `chatgpt-shell-post-prompt`.

**Comment by gnusupport** [comment]
Provided example:

```
(chatgpt-shell-post-prompt 
 "hello"
 "gpt-3.5-turbo"
 (lambda (response)
   (message "%s" response))
 (lambda (error)
   (message "%s" error)))
```

gives error:

```
user-error: Not in a shell [2 times]
```

Do you have a working example?

**Comment by xenodium** [comment]
Sorry, there's a regression in the async version (when you supply the lambdas). I'll look into fixing, but in the mean time, you can use the sync version via:

```emacs-lisp
(chatgpt-shell-post-prompt
 "hello"
 "gpt-3.5-turbo")
```

**Comment by xenodium** [comment]
@gnusupport as of https://github.com/xenodium/chatgpt-shell/commit/03f8edabb95c6ffc64050d79fdb3091532711b59, this should work again

```emacs-lisp
(chatgpt-shell-post-prompt
 "hello"
 "gpt-3.5-turbo"
 (lambda (response)
   (message "%s" response))
 (lambda (error)
   (message "%s" error)))
```

**Comment by gnusupport** [comment]
No, it doesn't. I get this error:

"We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)"

**Comment by xenodium** [comment]
The function parameters had changed. Updated docstring. Try this:

```emacs-lisp
(chatgpt-shell-post-prompt
 "hello"
 nil
 "gpt-3.5-turbo"
 (lambda (response pending)
   (message "%s" response))
 (lambda (error)
   (message "%s" error)))
```

**Comment by gnusupport** [comment]
Alright, thank you. I am far after this and basically I don't use the package anymore because I have such specific needs. Thank you much.
