### ISSUE TITLE
Error: `Error caused by user's config or system: config.el, (void-function chatgpt-shell--append-system-info)`

### ISSUE THREAD

**Issue by skunert** [xenodium/chatgpt-shell#94]
I am on the latest commit of this package and get the error message as shown in the title on startup.
I see that this has been added in the latest commit, maybe some error there?

**Comment by zkry** [comment]
Looks like that commit introduced a new function and tried to call it before it was defined. Looks to be simple to fix.

**Comment by xenodium** [comment]
Thank you @zkry for fixing.
