### ISSUE TITLE
Question: How to reset the context of an org-babel chatgpt 

### ISSUE THREAD

**Issue by falematte** [xenodium/chatgpt-shell#96]
In the shell I would simply write "clear". More on this, how to have two org-babel blocks share the same context?

**Comment by xenodium** [comment]
ob-chatgpt-shell blocks don't keep context by default, unless `:context t` is set.

The context is constructed by collecting previous blocks in the same file:

![ob](https://github.com/xenodium/chatgpt-shell/assets/8107219/27f6be39-5b0f-43db-aac8-3a185907633f)


More details at: https://github.com/xenodium/chatgpt-shell#context

**Comment by falematte** [comment]
I am not able to reproduce this?
![image](https://github.com/xenodium/chatgpt-shell/assets/25055204/ec1d3368-db2d-41f6-89af-2d247dc312f2)

**Comment by falematte** [comment]
Some other times the :context works fine. What could be the cause of this?

**Comment by xenodium** [comment]
The response in https://github.com/xenodium/chatgpt-shell/issues/96#issuecomment-1567131658 is aware of the context. The response acknowledged both pieces of context.

**Comment by falematte** [comment]
Yea, you are right. My bad.

**Comment by xenodium** [comment]
> Some other times the :context works fine. What could be the cause of this?

Temperature would control creativity/randomness, but this isn't currently one of the supported header args. Adding `:temperature` to `ob-chatgpt-shell.el` would be great. This is already handled in `chatgpt-shell.el` and the logic can be coped of over to `ob-chatgpt-shell.el`. Are you interested in contributing it?

**Comment by xenodium** [comment]
> org-babel-insert-result: Wrong type argument: markerp, nil

Please file a separate bug for this, so we can track/solve independently. Use `M-x toggle-debug-on-error` and post a stack trace, so I can look into it.

**Comment by xenodium** [comment]
> Temperature would control creativity/randomness, but this isn't currently one of the supported header args. Adding `:temperature` to `ob-chatgpt-shell.el`

@falematte filed #101 for this.

**Comment by xenodium** [comment]
One of the source blocks in context likley hasn't been executed and is missing `#+RESULTS:`.If you execute it, the error should go away. I'll have to add code to omit empty assistant entries to avoid proactively.

**Comment by xenodium** [comment]
>  I'll have to add code to omit empty assistant entries to avoid proactively.

https://github.com/xenodium/chatgpt-shell/commit/1860b3e8b94a9a2d76828906fcb1046a0bc04255 should do it. Give that a try.
